#!/usr/bin/env python3
"""Generate a Monte-Carlo Vt-mismatch variant of a TH-cell subckt.

Reads a .subckt from a SPICE file and rewrites every MOSFET line to carry an
independent per-device threshold shift DELVTO={AGAUSS(0, kvt*sigma, 1)}, where
sigma = A_VT / sqrt(W*L) is the Pelgrom local-mismatch std-dev (A_VT in V*um,
W/L in um). The PyMS runtime-callback path (PYMS_CALLBACK_PARAMS=DELVTO) makes
DELVTO reach the PSP103 threshold live, so Xyce .SAMPLING draws the samples.

Usage: gen_mc.py <in.sp> <subckt_name> <out.sp> [A_VT_mV_um]
"""
import re, sys, math

def um(tok):
    """Parse a SPICE length token like '0.7u' or '130n' -> micrometres."""
    m = re.match(r'([0-9.eE+-]+)\s*([a-zA-Z]*)$', tok)
    v = float(m.group(1)); u = m.group(2).lower()
    scale = {'':1.0, 'u':1.0, 'um':1.0, 'n':1e-3, 'nm':1e-3, 'p':1e-6, 'm':1e3}
    return v * scale.get(u, 1.0)

def gen(inp, subckt, outp, avt_mv_um=3.5):
    avt = avt_mv_um * 1e-3  # V*um
    lines = open(inp).read().splitlines()
    # slice out the requested .subckt ... .ends block
    body, inblk = [], False
    for ln in lines:
        s = ln.strip()
        if re.match(r'(?i)\.subckt\s+' + re.escape(subckt) + r'\b', s):
            inblk = True
        if inblk:
            body.append(ln)
        if inblk and re.match(r'(?i)\.ends', s):
            break
    if not body:
        sys.exit("subckt %s not found in %s" % (subckt, inp))
    out = []
    ndev = 0
    for ln in body:
        s = ln.strip()
        m = re.match(r'(?i)\.subckt\s+' + re.escape(subckt) + r'\b', s)
        if m:
            out.append(ln)
            out.append('.param kvt=1  ; overall Vt-mismatch scale (1 = nominal Pelgrom)')
            continue
        # MOSFET card: M<name> d g s b model W=.. L=..
        wm = re.search(r'(?i)\bW\s*=\s*(\S+)', ln)
        lm = re.search(r'(?i)\bL\s*=\s*(\S+)', ln)
        if re.match(r'(?i)\s*M\w', ln) and wm and lm and 'DELVTO' not in ln.upper():
            W = um(wm.group(1)); L = um(lm.group(1))
            sigma = avt / math.sqrt(W * L)   # volts
            out.append(ln.rstrip() +
                       ' DELVTO={AGAUSS(0,kvt*%.4e,1)}' % sigma +
                       '  ; sigma_Vt=%.1f mV (W=%.3g L=%.3g)' % (sigma*1e3, W, L))
            ndev += 1
        else:
            out.append(ln)
    with open(outp, 'w') as f:
        f.write('* Monte-Carlo Vt-mismatch variant of %s (from %s)\n' % (subckt, inp))
        f.write('* Auto-generated by gen_mc.py; A_Vt=%.1f mV*um; %d devices.\n'
                % (avt_mv_um, ndev))
        f.write('\n'.join(out) + '\n')
    print("wrote %s: %d devices with per-device DELVTO=AGAUSS" % (outp, ndev))

if __name__ == '__main__':
    a = sys.argv
    gen(a[1], a[2], a[3], float(a[4]) if len(a) > 4 else 3.5)
