#!/usr/bin/env python3
"""nulex gen_ncl_diff — self-contained equivalence TB: <top>_ncl vs <top>_plain.

Emits a single NVC testbench that drives the SAME random stimulus to the mapped
dual-rail NCL netlist (inputs ncl_encode'd) and the plain std_logic reference
(from the same gate netlist), clocks both, and asserts every decoded NCL output
equals the plain output every cycle. Proves the dual-rail transform is faithful
to the gates at full scale, with no external oracle.

Usage: gen_ncl_diff.py <ports.txt> <top> <out.vhd> [cycles]
"""
import sys

def main():
    ports_path, top, out = sys.argv[1:4]
    cycles = int(sys.argv[4]) if len(sys.argv) > 4 else 200
    ports = []
    for line in open(ports_path):
        f = line.split()
        if len(f) != 3: continue
        d, w, n = f[0], int(f[1]), f[2]
        if n == 'clk': continue
        ports.append((d, w, n))
    ins  = [p for p in ports if p[0] == 'input']
    outs = [p for p in ports if p[0] == 'output']
    total_in = sum(w for (_, w, _) in ins)
    ent = "tb_%s_diff" % top

    L = ["-- GENERATED by nulex gen_ncl_diff.py -- do not edit.",
         "library ieee; use ieee.std_logic_1164.all; use ieee.numeric_std.all;",
         "library ncl; use ncl.ncl.all;", "",
         f"entity {ent} is end entity;",
         f"architecture t of {ent} is",
         "    signal clk : std_logic := '0';",
         "    signal running : boolean := true;"]
    def ty_plain(w): return "std_logic" if w == 1 else f"std_logic_vector({w-1} downto 0)"
    def ty_ncl(w):   return "ncl_logic"  if w == 1 else f"ncl_logic_vector({w-1} downto 0)"
    for (d, w, n) in ins:
        L.append(f"    signal p_{n} : {ty_plain(w)};")
        L.append(f"    signal q_{n} : {ty_ncl(w)};")
    for (d, w, n) in outs:
        L.append(f"    signal po_{n} : {ty_plain(w)};")
        L.append(f"    signal no_{n} : {ty_ncl(w)};")
    L.append("begin")
    # NCL input encoders
    for (d, w, n) in ins:
        L.append(f"    q_{n} <= ncl_encode(p_{n});")
    # plain DUT
    L.append(f"    plain: entity work.{top}_plain port map (")
    pm = ["            clk => clk"] + [f"            {n} => p_{n}" for (_, _, n) in ins] \
         + [f"            {n} => po_{n}" for (_, _, n) in outs]
    L.append(",\n".join(pm) + ");")
    # ncl DUT
    L.append(f"    dut: entity work.{top}_ncl port map (")
    pm = ["            clk => clk"] + [f"            {n} => q_{n}" for (_, _, n) in ins] \
         + [f"            {n} => no_{n}" for (_, _, n) in outs]
    L.append(",\n".join(pm) + ");")
    L.append("""    clkgen: process begin
        wait for 5 ns;
        while running loop clk <= '1'; wait for 5 ns; clk <= '0'; wait for 5 ns; end loop;
        wait;
    end process;

    stim: process
        variable lfsr : std_logic_vector(31 downto 0) := x"1234abcd";
        variable R : std_logic_vector(%d downto 0);
        variable bad, cyc : integer := 0;
        procedure fill is       -- scalar-xor Galois LFSR (avoids numeric_std vector xor)
            variable fb : std_logic;
        begin
            for i in R'range loop
                fb := lfsr(31) xor lfsr(21) xor lfsr(1) xor lfsr(0);
                lfsr := lfsr(30 downto 0) & fb;
                R(i) := fb;
            end loop;
        end procedure;
    begin
        for c in 0 to %d loop
            fill;""" % (max(total_in - 1, 0), cycles))
    off = 0
    for (d, w, n) in ins:
        if w == 1:
            L.append(f"            p_{n} <= R({off});")
        else:
            L.append(f"            p_{n} <= R({off + w - 1} downto {off});")
        off += w
    L.append("            wait until clk = '0'; wait for 1 ns;")
    for (d, w, n) in outs:
        act = f"ncl_decode(no_{n})"
        exp = f"po_{n}"
        if w == 1:
            L.append(f"            if {act} /= {exp} then bad := bad + 1;")
            L.append(f'                if bad <= 30 then report "cyc " & integer\'image(cyc) & " {n} mismatch" severity warning; end if; end if;')
        else:
            L.append(f"            if {act} /= {exp} then bad := bad + 1;")
            L.append(f'                if bad <= 30 then report "cyc " & integer\'image(cyc) & " {n} mismatch a=" & to_hstring({act}) & " e=" & to_hstring({exp}) severity warning; end if; end if;')
    L.append("""            cyc := cyc + 1;
        end loop;
        running <= false;
        if bad = 0 then
            report "NCL-DIFF PASS: %s -- dual-rail NCL == plain gates over " & integer'image(cyc)
                 & " random cycles (every output every cycle)";
        else
            report "NCL-DIFF FAIL: " & integer'image(bad) & " mismatches" severity failure;
        end if;
        wait;
    end process;
end architecture;""" % top)
    open(out, "w").write("\n".join(L) + "\n")
    print(f"generated {out}: {ent}, {len(ins)} inputs ({total_in} bits) / {len(outs)} outputs, {cycles} cycles")

if __name__ == "__main__":
    main()
