#!/usr/bin/env python3
"""nulex map_ncl — yosys gate netlist (JSON) -> dual-rail NCL VHDL netlist.

Reads a yosys `write_json` netlist mapped to gate primitives
({$_AND_,$_OR_,$_XOR_,$_NAND_,$_NOR_,$_XNOR_,$_NOT_,$_MUX_} + $_DFF_P_/$_DFF_N_)
and emits a structural dual-rail NCL netlist instantiating the nulex gate
entities (lib/ncl_gates.vhd), one per cell.

Bindings:
  * combinational cones -> QDI dual-rail (each 1-bit net -> one ncl_logic;
    constants -> NCL_DATA0/1).
  * registers ($_DFF_) -> ncl_dff = the SYNC-EMULATION binding (clocked
    dual-rail latch on an ordinary single-rail clock; no NULL cycling). The
    true QDI register is future work (no sequential NCL cell exists yet).
  Clock nets stay single-rail std_logic; data nets are dual-rail ncl_logic.

Usage: map_ncl.py <netlist.json> <top> <out.vhd>
"""
import json, sys

# combinational gate cell -> (entity, [(entity_port, json_port)...], out_json_port, out_entity_port)
GATES = {
    "$_AND_":  ("ncl_and2",  [("a","A"),("b","B")], "Y", "z"),
    "$_NAND_": ("ncl_nand2", [("a","A"),("b","B")], "Y", "z"),
    "$_OR_":   ("ncl_or2",   [("a","A"),("b","B")], "Y", "z"),
    "$_NOR_":  ("ncl_nor2",  [("a","A"),("b","B")], "Y", "z"),
    "$_XOR_":  ("ncl_xor2",  [("a","A"),("b","B")], "Y", "z"),
    "$_XNOR_": ("ncl_xnor2", [("a","A"),("b","B")], "Y", "z"),
    "$_NOT_":  ("ncl_inv",   [("a","A")],           "Y", "z"),
    "$_MUX_":  ("ncl_mux2",  [("s","S"),("a","A"),("b","B")], "Y", "y"),
}
DFFS = {"$_DFF_P_"}   # posedge; extend with negedge/reset variants as needed

def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    jpath, top, out = sys.argv[1:]
    d = json.load(open(jpath))
    if top not in d["modules"]:
        sys.exit(f"top '{top}' not in {list(d['modules'])}")
    m = d["modules"][top]
    ports, cells = m["ports"], m["cells"]

    # clock nets = anything feeding a DFF clock (C). These stay single-rail.
    clock_nets = set()
    for c in cells.values():
        if c["type"].startswith(("$_DFF", "$_SDFF", "$_DFFE", "$_DLATCH")):
            for b in c["connections"].get("C", []):
                if isinstance(b, int): clock_nets.add(b)

    # every integer net used anywhere
    allnets = set()
    def note(bits):
        for b in bits:
            if isinstance(b, int): allnets.add(b)
    for p in ports.values(): note(p["bits"])
    for c in cells.values():
        if c["type"] == "$scopeinfo": continue
        for conn in c["connections"].values(): note(conn)
    dual_nets = allnets - clock_nets

    def dsig(bit):   # data (dual-rail) net or constant -> VHDL expr
        if isinstance(bit, int): return f"n{bit}"
        if bit == "0": return "NCL_DATA0"
        if bit == "1": return "NCL_DATA1"
        raise SystemExit(f"unsupported constant data bit {bit!r}")
    def csig(bit):   # clock (single-rail) net
        if isinstance(bit, int): return f"c{bit}"
        raise SystemExit(f"clock bit must be a net, got {bit!r}")

    L = ["-- GENERATED by nulex map_ncl.py -- do not edit.",
         f"-- dual-rail NCL netlist for yosys module '{top}' "
         "(combinational=QDI dual-rail, registers=sync-emulation).",
         "library IEEE; use IEEE.std_logic_1164.all; library ncl; use ncl.ncl.all;",
         "", f"entity {top}_ncl is"]

    # ports: clock (1-bit input on a clock net) -> std_logic; else dual-rail
    port_is_clock = {}
    plines = []
    for pname, p in ports.items():
        w = len(p["bits"]); dir_ = "in" if p["direction"] == "input" else "out"
        is_clk = (w == 1 and p["direction"] == "input" and p["bits"][0] in clock_nets)
        port_is_clock[pname] = is_clk
        if is_clk:
            plines.append(f"    {pname} : in std_logic")
        else:
            ty = "ncl_logic" if w == 1 else f"ncl_logic_vector({w-1} downto 0)"
            plines.append(f"    {pname} : {dir_} {ty}")
    L.append("  port (\n" + ";\n".join(plines) + "\n  );")
    L.append(f"end entity {top}_ncl;")
    L.append("")
    L.append(f"architecture ncl_net of {top}_ncl is")
    ids = sorted(dual_nets); CH = 16
    for i in range(0, len(ids), CH):
        L.append("  signal " + ", ".join(f"n{b}" for b in ids[i:i+CH]) + " : ncl_logic;")
    if clock_nets:
        L.append("  signal " + ", ".join(f"c{b}" for b in sorted(clock_nets)) + " : std_logic;")
    L.append("begin")

    # wire ports to nets
    for pname, p in ports.items():
        w = len(p["bits"])
        if port_is_clock[pname]:
            L.append(f"  {csig(p['bits'][0])} <= {pname};")
            continue
        for i, b in enumerate(p["bits"]):
            acc = pname if w == 1 else f"{pname}({i})"
            if p["direction"] == "input":
                if isinstance(b, int): L.append(f"  n{b} <= {acc};")
            else:
                L.append(f"  {acc} <= {dsig(b)};")

    # instantiate an entity per cell
    gi = 0
    for cname, c in cells.items():
        t = c["type"]; conn = c["connections"]
        if t == "$scopeinfo":
            continue                      # yosys hierarchy metadata, no logic
        if t == "$_BUF_":
            L.append(f"  n{conn['Y'][0]} <= {dsig(conn['A'][0])};"); continue
        if t in DFFS:
            L.append(f"  r{gi}: entity work.ncl_dff port map "
                     f"(clk => {csig(conn['C'][0])}, d => {dsig(conn['D'][0])}, "
                     f"q => n{conn['Q'][0]});")
            gi += 1; continue
        if t.startswith(("$_DFF", "$_SDFF", "$_DFFE", "$_DLATCH")):
            sys.exit(f"sequential cell {t} not supported yet "
                     f"(use dfflegalize -cell $_DFF_P_ to fold reset into logic)")
        if t not in GATES:
            sys.exit(f"unhandled cell type {t} (cell {cname})")
        ent, ins, outp, oport = GATES[t]
        pm = [f"{ep} => {dsig(conn[jp][0])}" for ep, jp in ins]
        pm.append(f"{oport} => n{conn[outp][0]}")
        L.append(f"  g{gi}: entity work.{ent} port map ({', '.join(pm)});")
        gi += 1

    L.append(f"end architecture ncl_net;")
    open(out, "w").write("\n".join(L) + "\n")
    ncomb = sum(1 for c in cells.values() if c["type"] in GATES)
    nff   = sum(1 for c in cells.values() if c["type"] in DFFS)
    print(f"wrote {out}: {ncomb} comb gates, {nff} registers, "
          f"{len(dual_nets)} data nets, {len(clock_nets)} clock net(s), {len(ports)} ports")

if __name__ == "__main__":
    main()
