#!/usr/bin/env python3
"""nulex map_plain — yosys gate netlist (JSON) -> plain std_logic VHDL netlist.

A single-rail reference emitter: the SAME gate netlist map_ncl.py maps to
dual-rail NCL, emitted as ordinary std_logic boolean logic + clocked registers.
Simulated alongside the NCL netlist under identical stimulus, it is the
self-contained equivalence reference proving the dual-rail transform is
faithful to the gates (no external oracle needed). Same cell subset as
map_ncl.py; $_DFF_P_ -> a clocked register; $scopeinfo skipped.

Usage: map_plain.py <netlist.json> <top> <out.vhd>
"""
import json, sys

BIN = {"$_AND_": "and", "$_OR_": "or", "$_XOR_": "xor",
       "$_NAND_": "nand", "$_NOR_": "nor", "$_XNOR_": "xnor"}

def bit(b):
    if isinstance(b, int): return f"n{b}"
    if b == "0": return "'0'"
    if b == "1": return "'1'"
    raise SystemExit(f"bad const {b!r}")

def main():
    jpath, top, out = sys.argv[1:4]
    m = json.load(open(jpath))["modules"][top]
    ports, cells = m["ports"], m["cells"]
    allnets = set()
    def note(bs):
        for b in bs:
            if isinstance(b, int): allnets.add(b)
    for p in ports.values(): note(p["bits"])
    for c in cells.values():
        if c["type"] == "$scopeinfo": continue
        for cn in c["connections"].values(): note(cn)

    L = ["-- GENERATED by nulex map_plain.py -- plain std_logic reference.",
         "library IEEE; use IEEE.std_logic_1164.all;", "",
         f"entity {top}_plain is", "  port ("]
    pl = []
    for pn, p in ports.items():
        w = len(p["bits"]); d = "in" if p["direction"] == "input" else "out"
        ty = "std_logic" if w == 1 else f"std_logic_vector({w-1} downto 0)"
        pl.append(f"    {pn} : {d} {ty}")
    L.append(";\n".join(pl) + "\n  );")
    L.append(f"end entity {top}_plain;")
    L.append(f"architecture gates of {top}_plain is")
    ids = sorted(allnets); CH = 20
    for i in range(0, len(ids), CH):
        L.append("  signal " + ", ".join(f"n{b}" for b in ids[i:i+CH]) + " : std_logic := '0';")
    L.append("begin")
    # port wiring
    for pn, p in ports.items():
        w = len(p["bits"])
        for i, b in enumerate(p["bits"]):
            acc = pn if w == 1 else f"{pn}({i})"
            if p["direction"] == "input":
                if isinstance(b, int): L.append(f"  n{b} <= {acc};")
            else:
                L.append(f"  {acc} <= {bit(b)};")
    # combinational gates + collect DFFs for one clocked process
    dffs = []
    for cn, c in cells.items():
        t = c["type"]; k = c["connections"]
        if t == "$scopeinfo": continue
        if t in BIN:
            L.append(f"  n{k['Y'][0]} <= {bit(k['A'][0])} {BIN[t]} {bit(k['B'][0])};")
        elif t == "$_NOT_":
            L.append(f"  n{k['Y'][0]} <= not {bit(k['A'][0])};")
        elif t == "$_MUX_":
            L.append(f"  n{k['Y'][0]} <= {bit(k['B'][0])} when {bit(k['S'][0])} = '1' else {bit(k['A'][0])};")
        elif t == "$_BUF_":
            L.append(f"  n{k['Y'][0]} <= {bit(k['A'][0])};")
        elif t == "$_DFF_P_":
            dffs.append((k['C'][0], k['D'][0], k['Q'][0]))
        else:
            sys.exit(f"map_plain: unhandled {t}")
    if dffs:
        clk = f"n{dffs[0][0]}"   # single clock domain
        L.append(f"  process({clk}) begin")
        L.append(f"    if rising_edge({clk}) then")
        for (_, d, q) in dffs:
            L.append(f"      n{q} <= {bit(d)};")
        L.append("    end if;")
        L.append("  end process;")
    L.append(f"end architecture gates;")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"wrote {out}: {sum(1 for c in cells.values() if c['type'] in BIN or c['type'] in ('$_NOT_','$_MUX_'))} gates, "
          f"{len(dffs)} registers, {len(allnets)} nets")

if __name__ == "__main__":
    main()
