#!/usr/bin/env python3
"""nulex map_actor_c — yosys gate netlist (JSON) -> a compiled event-driven
("actor") C simulator. The C form of actor_sim.py: a register is an ACTOR that
fires only when its D changed since it last captured, so idle state costs zero.

Emits one self-contained C file (netlist baked in as static arrays) with:
  - run_obliv : evaluate every comb gate (topological) + clock every register
                each cycle -- the sync/clocked-ncl_dff cost.
  - run_actor : event-driven; only changed gates + fired (dirty) registers.
  Both produce the same output-trace hash (verified). Plus a driver:
    <exe> verify  [cycles activity]  -- assert run_actor == run_obliv, sweep activity
    <exe> bench   [cycles]           -- wall-clock run_actor vs run_obliv, sweep activity
    <exe> check   <stim_file>        -- run_obliv on a dumped stimulus, compare its
                                        output trace to the dump (codegen fidelity vs
                                        actor_sim.py --dump)

Usage: map_actor_c.py <netlist.json> <top> <out.c>
"""
import json, sys

TYPES = {"$_AND_": 0, "$_OR_": 1, "$_XOR_": 2, "$_NAND_": 3, "$_NOR_": 4,
         "$_XNOR_": 5, "$_NOT_": 6, "$_BUF_": 7, "$_MUX_": 8}

def carr(name, ty, vals):
    out = ["static const %s %s[%d] = {" % (ty, name, max(len(vals),1))]
    line = "  "
    for i, x in enumerate(vals):
        s = str(x) + ","
        if len(line) + len(s) > 110: out.append(line); line = "  "
        line += s
    out.append(line); out.append("};")
    return "\n".join(out)

def main():
    jpath, top, outc = sys.argv[1:4]
    m = json.load(open(jpath))["modules"][top]
    ports, cells = m["ports"], m["cells"]

    # dense net indices: 0 = const-0, 1 = const-1, integer nets -> 2..
    nidx = {}
    def N(b):
        if b == "0": return 0
        if b == "1": return 1
        if isinstance(b, int):
            if b not in nidx: nidx[b] = len(nidx) + 2
            return nidx[b]
        raise SystemExit("bad bit %r" % b)

    gtype, ga, gb, gs, gy = [], [], [], [], []
    regs_d, regs_q, regs_r = [], [], []   # regs_r: async active-low reset net (dense), or -1
    cons = {}   # net -> [gate idx]  (real, non-const inputs only)
    dreg = {}   # net -> [reg idx]  (triggered by D input OR reset change)
    def add_cons(net, gi):
        if net >= 2: cons.setdefault(net, []).append(gi)
    for c in cells.values():
        t = c["type"]; k = c["connections"]
        if t == "$scopeinfo": continue
        if t in ("$_DFF_P_", "$_DFF_PN0_"):
            d, q = N(k["D"][0]), N(k["Q"][0])
            r = N(k["R"][0]) if t == "$_DFF_PN0_" else -1
            ri = len(regs_d); regs_d.append(d); regs_q.append(q); regs_r.append(r)
            if d >= 2: dreg.setdefault(d, []).append(ri)
            if r >= 2: dreg.setdefault(r, []).append(ri)
            continue
        if t not in TYPES: sys.exit("unhandled cell " + t)
        gi = len(gtype)
        a = N(k["A"][0]); b = s = 0
        if t in ("$_NOT_", "$_BUF_"):
            pass
        elif t == "$_MUX_":
            b = N(k["B"][0]); s = N(k["S"][0])
        else:
            b = N(k["B"][0])
        gtype.append(TYPES[t]); ga.append(a); gb.append(b); gs.append(s); gy.append(N(k["Y"][0]))
        add_cons(a, gi)
        if t == "$_MUX_": add_cons(b, gi); add_cons(s, gi)
        elif t not in ("$_NOT_", "$_BUF_"): add_cons(b, gi)

    NNETS = len(nidx) + 2
    NG = len(gtype); NR = len(regs_d)

    # consumers CSR
    cons_off = [0]*(NNETS+1); flat_c = []
    for n in range(NNETS):
        flat_c.extend(cons.get(n, ())); cons_off[n+1] = len(flat_c)
    dreg_off = [0]*(NNETS+1); flat_d = []
    for n in range(NNETS):
        flat_d.extend(dreg.get(n, ())); dreg_off[n+1] = len(flat_d)

    # topo order of gates (sources = nets not driven by a gate)
    drv = {}                       # net -> gate that drives it
    for gi in range(NG): drv[gy[gi]] = gi
    order = []; seen = [0]*NG
    for start in range(NG):
        if seen[start]: continue
        stack = [(start, False)]
        while stack:
            g, done = stack.pop()
            if done: order.append(g); continue
            if seen[g]: continue
            seen[g] = 1; stack.append((g, True))
            for net in (ga[g], gb[g], gs[g]):
                if net in drv and not seen[drv[net]]:
                    stack.append((drv[net], False))

    # io: flattened input net indices (exclude clk), output bit net indices
    in_nets, out_bits = [], []
    for pn, p in ports.items():
        if p["direction"] == "input" and pn != "clk":
            for b in p["bits"]:
                if isinstance(b, int): in_nets.append(N(b))
    for pn, p in ports.items():
        if p["direction"] == "output":
            for b in p["bits"]: out_bits.append(N(b))

    W = []
    W.append("/* GENERATED by nulex map_actor_c.py from %s (top %s) */" % (jpath, top))
    W.append("#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <stdint.h>\n#include <time.h>")
    W.append("#define NNETS %d\n#define NG %d\n#define NR %d\n#define NIN %d\n#define NOUT %d"
             % (NNETS, NG, NR, len(in_nets), len(out_bits)))
    W.append(carr("g_type","uint8_t",gtype)); W.append(carr("g_a","int32_t",ga))
    W.append(carr("g_b","int32_t",gb)); W.append(carr("g_s","int32_t",gs)); W.append(carr("g_y","int32_t",gy))
    W.append(carr("cons_off","int32_t",cons_off)); W.append(carr("cons_idx","int32_t",flat_c))
    W.append(carr("r_d","int32_t",regs_d)); W.append(carr("r_q","int32_t",regs_q))
    W.append(carr("r_r","int32_t",regs_r))   # async reset net per reg, or -1
    W.append(carr("dreg_off","int32_t",dreg_off)); W.append(carr("dreg_idx","int32_t",flat_d))
    W.append(carr("topo","int32_t",order))
    W.append(carr("in_nets","int32_t",in_nets)); W.append(carr("out_bits","int32_t",out_bits))
    W.append(r"""
static int8_t val[NNETS];
/* reset-aware captured value: async active-low reset (r_r>=0) forces 0 */
#define RQ(r) ((r_r[r] >= 0 && !val[r_r[r]]) ? 0 : val[r_d[r]])
static inline int ev(int g){
    int a=val[g_a[g]],b=val[g_b[g]],s=val[g_s[g]];
    switch(g_type[g]){
        case 0:return a&b; case 1:return a|b; case 2:return a^b;
        case 3:return !(a&b); case 4:return !(a|b); case 5:return !(a^b);
        case 6:return !a; case 7:return a; default:return s?b:a;
    }
}
static inline uint64_t ocheck(void){
    uint64_t h=1469598103934665603ULL;
    for(int i=0;i<NOUT;i++){ h^=(uint64_t)val[out_bits[i]]; h*=1099511628211ULL; }
    return h;
}
static void reset_state(void){ memset(val,0,sizeof val); val[1]=1; }
static uint32_t rng;
static inline uint32_t xr(void){ rng^=rng<<13; rng^=rng>>17; rng^=rng<<5; return rng; }

/* OBLIVIOUS: every gate (topo) + every register, every cycle. */
static uint64_t run_obliv(int cycles,uint32_t thresh,uint32_t seed,uint64_t*work){
    reset_state(); rng=seed; uint64_t w=0,trace=1469598103934665603ULL;
    static int8_t nd[NR>0?NR:1];
    for(int c=0;c<cycles;c++){
        for(int i=0;i<NIN;i++) if(xr()<thresh) val[in_nets[i]]=xr()&1;
        for(int i=0;i<NG;i++){ int g=topo[i]; val[g_y[g]]=ev(g); w++; }
        uint64_t oc=ocheck(); trace=(trace^oc)*1099511628211ULL;
        for(int r=0;r<NR;r++) nd[r]=RQ(r);
        for(int r=0;r<NR;r++){ val[r_q[r]]=nd[r]; w++; }
    }
    *work=w; return trace;
}

/* ACTOR: event-driven; only changed gates + fired (dirty) registers. */
static int32_t *gstk; static uint8_t *ginq;
static int32_t *rstk; static uint8_t *rinr; static int32_t *upd_r; static int8_t *upd_v;
static void alloc_wl(void){
    gstk=malloc(sizeof(int32_t)*(NG+1)); ginq=calloc(NG,1);
    rstk=malloc(sizeof(int32_t)*(NR+1)); rinr=calloc(NR,1);
    upd_r=malloc(sizeof(int32_t)*(NR+1)); upd_v=malloc(NR+1);
}
static uint64_t run_actor(int cycles,uint32_t thresh,uint32_t seed,uint64_t*work){
    reset_state(); rng=seed; uint64_t w=0,trace=1469598103934665603ULL;
    int gt=0, rt=0;
    memset(ginq,0,NG); memset(rinr,0,NR);
    #define GPUSH(g) do{ int _g=(g); if(!ginq[_g]){ ginq[_g]=1; gstk[gt++]=_g; } }while(0)
    #define RDIRTY(net) do{ for(int _j=dreg_off[net];_j<dreg_off[(net)+1];_j++){ int _r=dreg_idx[_j]; if(!rinr[_r]){ rinr[_r]=1; rstk[rt++]=_r; } } }while(0)
    #define DRAIN() while(gt){ int g=gstk[--gt]; ginq[g]=0; int ny=ev(g); w++; int yn=g_y[g]; \
        if(ny!=val[yn]){ val[yn]=ny; for(int _k=cons_off[yn];_k<cons_off[yn+1];_k++) GPUSH(cons_idx[_k]); RDIRTY(yn); } }
    /* prime: full topo eval so all nets are defined, then dirty regs where D!=Q */
    for(int i=0;i<NG;i++){ int g=topo[i]; val[g_y[g]]=ev(g); }
    for(int r=0;r<NR;r++) if(RQ(r)!=val[r_q[r]]){ rinr[r]=1; rstk[rt++]=r; }
    for(int c=0;c<cycles;c++){
        for(int i=0;i<NIN;i++) if(xr()<thresh){ int nv=xr()&1; int n=in_nets[i];
            if(val[n]!=nv){ val[n]=nv; for(int _k=cons_off[n];_k<cons_off[n+1];_k++) GPUSH(cons_idx[_k]); RDIRTY(n); } }
        DRAIN();
        uint64_t oc=ocheck(); trace=(trace^oc)*1099511628211ULL;
        /* clock: two-phase capture of dirty regs, then apply */
        int nu=0;
        for(int i=0;i<rt;i++){ int r=rstk[i]; rinr[r]=0; w++; int nv=RQ(r);
            if(nv!=val[r_q[r]]){ upd_r[nu]=r; upd_v[nu]=nv; nu++; } }
        rt=0;
        for(int i=0;i<nu;i++){ int r=upd_r[i]; int qn=r_q[r]; val[qn]=upd_v[i];
            for(int _k=cons_off[qn];_k<cons_off[qn+1];_k++) GPUSH(cons_idx[_k]); RDIRTY(qn); }
        DRAIN();
    }
    *work=w; return trace;
}
static double now(void){ struct timespec t; clock_gettime(CLOCK_MONOTONIC,&t); return t.tv_sec+t.tv_nsec*1e-9; }

int main(int argc,char**argv){
    alloc_wl();
    const char*mode = argc>1?argv[1]:"verify";
    if(!strcmp(mode,"check")){
        FILE*f=fopen(argv[2],"r"); if(!f){perror("open");return 1;}
        int cyc,nin,nout; if(fscanf(f,"%d %d %d",&cyc,&nin,&nout)!=3)return 2;
        if(nin!=NIN||nout!=NOUT){ fprintf(stderr,"stim NIN/NOUT %d/%d != %d/%d\n",nin,nout,NIN,NOUT); return 3; }
        reset_state(); static int8_t nd[NR>0?NR:1]; int bad=0;
        char*ob=malloc(NOUT+2);
        for(int c=0;c<cyc;c++){
            int nch; if(fscanf(f,"%d",&nch)!=1)return 4;
            for(int j=0;j<nch;j++){ int pos,v; if(fscanf(f,"%d %d",&pos,&v)!=2)return 4; val[in_nets[pos]]=v; }
            for(int i=0;i<NG;i++){ int g=topo[i]; val[g_y[g]]=ev(g); }
            if(fscanf(f,"%s",ob)!=1)return 4;
            for(int i=0;i<NOUT;i++){ int want=ob[i]-'0'; if(want!=val[out_bits[i]]) bad++; }
            for(int r=0;r<NR;r++) nd[r]=RQ(r);
            for(int r=0;r<NR;r++) val[r_q[r]]=nd[r];
        }
        printf("check: %d cycles, %d output-bit mismatches vs actor_sim.py oblivious dump -> %s\n",
               cyc,bad, bad?"*** CODEGEN MISMATCH ***":"OK (codegen faithful)");
        return bad?1:0;
    }
    int cycles = argc>2?atoi(argv[2]):20000;
    printf("NG=%d gates, NR=%d regs, NIN=%d, NOUT=%d, %d cycles\n", NG,NR,NIN,NOUT,cycles);
    if(!strcmp(mode,"verify")){
        printf("%10s %10s %10s  %s\n","inj/1e6","actor_ops","obliv_ops","equiv");
        uint32_t ths[]={4294,42949,429496,4294967,42949672,214748364,429496729,2147483647,4294967295u};
        for(unsigned t=0;t<sizeof ths/sizeof*ths;t++){
            uint64_t wo,wa; uint64_t co=run_obliv(cycles,ths[t],12345,&wo);
            uint64_t ca=run_actor(cycles,ths[t],12345,&wa);
            printf("%10.4f %10llu %10llu  %s\n", ths[t]/4294.967296,
                   (unsigned long long)wa,(unsigned long long)wo, co==ca?"OK":"*** MISMATCH ***");
        }
        return 0;
    }
    /* bench */
    printf("%9s %10s %10s %9s %9s %8s\n","act%","obliv_ms","actor_ms","spd","obliv_ops","actor_ops");
    uint32_t ths[]={42949,214748,429496,2147483,4294967,21474836,42949672,214748364,429496729u,2147483647u,4294967295u};
    for(unsigned t=0;t<sizeof ths/sizeof*ths;t++){
        uint64_t wo,wa;
        double t0=now(); uint64_t co=run_obliv(cycles,ths[t],12345,&wo); double t1=now();
        double t2=now(); uint64_t ca=run_actor(cycles,ths[t],12345,&wa); double t3=now();
        printf("%8.3f%% %10.1f %10.1f %8.2fx %9llu %9llu  %s\n",
               100.0*wa/(double)(wo?wo:1), (t1-t0)*1e3,(t3-t2)*1e3,(t1-t0)/(t3-t2),
               (unsigned long long)wo,(unsigned long long)wa, co==ca?"":"*MISMATCH*");
    }
    return 0;
}
""")
    open(outc, "w").write("\n".join(W) + "\n")
    print("wrote %s: %d gates, %d regs, %d nets, %d in / %d out"
          % (outc, NG, NR, NNETS, len(in_nets), len(out_bits)))

if __name__ == "__main__":
    main()
