#!/usr/bin/env python3
"""nulex map_ncl — yosys gate netlist (JSON) -> dual-rail NCL VHDL netlist.

Reads a yosys `write_json` netlist mapped to the abc/simplemap gate primitives
({$_AND_,$_OR_,$_XOR_,$_NAND_,$_NOR_,$_XNOR_,$_NOT_,$_MUX_}) and emits a
structural dual-rail NCL netlist that instantiates the nulex gate entities
(lib/ncl_gates.vhd), one per cell.  Each 1-bit yosys net -> one ncl_logic
signal; constants map to NCL_DATA0/1; the whole thing is the correct-by-
construction QDI binding of the combinational cone.

This is the P3->P4 "netlist mapper" (ASYNC-PLAN frontend/yosys_reader). It does
NOT handle sequential cells yet ($_DFF_*): those are a sync-emulation binding
until a sequential NCL register cell exists.

Usage: map_ncl.py <netlist.json> <top> <out.vhd>
"""
import json, sys

# yosys gate cell -> (nulex entity, [(entity_port, json_port)...], output_json_port)
GATES = {
    "$_AND_":  ("ncl_and2",  [("a","A"),("b","B")], "Y"),
    "$_NAND_": ("ncl_nand2", [("a","A"),("b","B")], "Y"),
    "$_OR_":   ("ncl_or2",   [("a","A"),("b","B")], "Y"),
    "$_NOR_":  ("ncl_nor2",  [("a","A"),("b","B")], "Y"),
    "$_XOR_":  ("ncl_xor2",  [("a","A"),("b","B")], "Y"),
    "$_XNOR_": ("ncl_xnor2", [("a","A"),("b","B")], "Y"),
    "$_NOT_":  ("ncl_inv",   [("a","A")],           "Y"),
    "$_MUX_":  ("ncl_mux2",  [("s","S"),("a","A"),("b","B")], "Y"),
    # $_BUF_ handled specially (direct wire), $_DFF_* rejected (see below)
}

def bit_sig(bit):
    """Map a json 'bit' (int net id, or const '0'/'1') to a VHDL expression."""
    if isinstance(bit, int):
        return f"n{bit}"
    if bit == "0": return "NCL_DATA0"
    if bit == "1": return "NCL_DATA1"
    raise SystemExit(f"unsupported constant bit {bit!r} (x/z not in the value domain)")

def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    jpath, top, out = sys.argv[1:]
    d = json.load(open(jpath))
    if top not in d["modules"]:
        sys.exit(f"top '{top}' not in {list(d['modules'])}")
    m = d["modules"][top]
    ports, cells, netnames = m["ports"], m["cells"], m.get("netnames", {})

    # collect every integer net id used anywhere -> declare a signal per net
    nets = set()
    def note(bits):
        for b in bits:
            if isinstance(b, int): nets.add(b)
    for p in ports.values(): note(p["bits"])
    for c in cells.values():
        for conn in c["connections"].values(): note(conn)

    L = []
    L.append("-- GENERATED by nulex map_ncl.py -- do not edit.")
    L.append(f"-- dual-rail NCL netlist for yosys module '{top}'.")
    L.append("library IEEE; use IEEE.std_logic_1164.all; library ncl; use ncl.ncl.all;")
    L.append("")
    # entity: dual-rail ports (vector if >1 bit, scalar ncl_logic if 1 bit)
    L.append(f"entity {top}_ncl is")
    plines = []
    for pname, p in ports.items():
        w = len(p["bits"]); dir_ = "in" if p["direction"] == "input" else "out"
        ty = "ncl_logic" if w == 1 else f"ncl_logic_vector({w-1} downto 0)"
        plines.append(f"    {pname} : {dir_} {ty}")
    L.append("  port (\n" + ";\n".join(plines) + "\n  );")
    L.append(f"end entity {top}_ncl;")
    L.append("")
    L.append(f"architecture ncl_net of {top}_ncl is")
    # signal per internal net (port-bit nets included; driven by the port wiring)
    if nets:
        decl = ", ".join(f"n{b}" for b in sorted(nets))
        # break long decls
        ids = sorted(nets); CH = 16
        for i in range(0, len(ids), CH):
            L.append("  signal " + ", ".join(f"n{b}" for b in ids[i:i+CH]) + " : ncl_logic;")
    L.append("begin")

    # wire input-port bits into their net signals; output-port bits out
    for pname, p in ports.items():
        w = len(p["bits"])
        for i, b in enumerate(p["bits"]):
            acc = pname if w == 1 else f"{pname}({i})"
            if p["direction"] == "input":
                if isinstance(b, int):
                    L.append(f"  n{b} <= {acc};")
                # a constant input-port bit would be odd; skip
            else:  # output
                L.append(f"  {acc} <= {bit_sig(b)};")

    # instantiate a nulex entity per gate cell
    gi = 0
    for cname, c in cells.items():
        t = c["type"]; conn = c["connections"]
        if t == "$_BUF_":
            y = conn["Y"][0]; a = conn["A"][0]
            L.append(f"  n{y} <= {bit_sig(a)};")
            continue
        if t.startswith("$_DFF") or t.startswith("$_SDFF") or t.startswith("$_DLATCH"):
            sys.exit(f"sequential cell {t} not supported yet (sync-emulation binding TODO)")
        if t not in GATES:
            sys.exit(f"unhandled cell type {t} (cell {cname})")
        ent, ins, outp = GATES[t]
        y = conn[outp][0]
        pm = [f"{ep} => {bit_sig(conn[jp][0])}" for ep, jp in ins]
        pm.append(f"z => n{y}" if ent != "ncl_mux2" else f"y => n{y}")
        L.append(f"  g{gi}: entity work.{ent} port map ({', '.join(pm)});")
        gi += 1

    L.append(f"end architecture ncl_net;")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"wrote {out}: {gi} gate cells, {len(nets)} nets, "
          f"{len(ports)} ports")

if __name__ == "__main__":
    main()
