/* Generated by Yosys 0.68+64 (git sha1 bd5c524dc, Release, GNU /usr/bin/c++ 11.4.0) */

module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val);
  input clk;
  wire clk;
  input [31:0] req_msg;
  wire [31:0] req_msg;
  output req_rdy;
  wire req_rdy;
  input req_val;
  wire req_val;
  input reset;
  wire reset;
  output [15:0] resp_msg;
  wire [15:0] resp_msg;
  input resp_rdy;
  wire resp_rdy;
  output resp_val;
  wire resp_val;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire \ctrl$a_reg_en[0] ;
  wire \ctrl$b_reg_en[0] ;
  wire \ctrl.state.out[1] ;
  wire \ctrl.state.out[2] ;
  wire \dpath.a_lt_b$in0[0] ;
  wire \dpath.a_lt_b$in0[10] ;
  wire \dpath.a_lt_b$in0[11] ;
  wire \dpath.a_lt_b$in0[12] ;
  wire \dpath.a_lt_b$in0[13] ;
  wire \dpath.a_lt_b$in0[14] ;
  wire \dpath.a_lt_b$in0[15] ;
  wire \dpath.a_lt_b$in0[1] ;
  wire \dpath.a_lt_b$in0[2] ;
  wire \dpath.a_lt_b$in0[3] ;
  wire \dpath.a_lt_b$in0[4] ;
  wire \dpath.a_lt_b$in0[5] ;
  wire \dpath.a_lt_b$in0[6] ;
  wire \dpath.a_lt_b$in0[7] ;
  wire \dpath.a_lt_b$in0[8] ;
  wire \dpath.a_lt_b$in0[9] ;
  wire \dpath.a_lt_b$in1[0] ;
  wire \dpath.a_lt_b$in1[10] ;
  wire \dpath.a_lt_b$in1[11] ;
  wire \dpath.a_lt_b$in1[12] ;
  wire \dpath.a_lt_b$in1[13] ;
  wire \dpath.a_lt_b$in1[14] ;
  wire \dpath.a_lt_b$in1[15] ;
  wire \dpath.a_lt_b$in1[1] ;
  wire \dpath.a_lt_b$in1[2] ;
  wire \dpath.a_lt_b$in1[3] ;
  wire \dpath.a_lt_b$in1[4] ;
  wire \dpath.a_lt_b$in1[5] ;
  wire \dpath.a_lt_b$in1[6] ;
  wire \dpath.a_lt_b$in1[7] ;
  wire \dpath.a_lt_b$in1[8] ;
  wire \dpath.a_lt_b$in1[9] ;
  wire \dpath.a_mux$out[0] ;
  wire \dpath.a_mux$out[10] ;
  wire \dpath.a_mux$out[11] ;
  wire \dpath.a_mux$out[12] ;
  wire \dpath.a_mux$out[13] ;
  wire \dpath.a_mux$out[14] ;
  wire \dpath.a_mux$out[15] ;
  wire \dpath.a_mux$out[1] ;
  wire \dpath.a_mux$out[2] ;
  wire \dpath.a_mux$out[3] ;
  wire \dpath.a_mux$out[4] ;
  wire \dpath.a_mux$out[5] ;
  wire \dpath.a_mux$out[6] ;
  wire \dpath.a_mux$out[7] ;
  wire \dpath.a_mux$out[8] ;
  wire \dpath.a_mux$out[9] ;
  wire \dpath.b_mux$out[0] ;
  wire \dpath.b_mux$out[10] ;
  wire \dpath.b_mux$out[11] ;
  wire \dpath.b_mux$out[12] ;
  wire \dpath.b_mux$out[13] ;
  wire \dpath.b_mux$out[14] ;
  wire \dpath.b_mux$out[15] ;
  wire \dpath.b_mux$out[1] ;
  wire \dpath.b_mux$out[2] ;
  wire \dpath.b_mux$out[3] ;
  wire \dpath.b_mux$out[4] ;
  wire \dpath.b_mux$out[5] ;
  wire \dpath.b_mux$out[6] ;
  wire \dpath.b_mux$out[7] ;
  wire \dpath.b_mux$out[8] ;
  wire \dpath.b_mux$out[9] ;
  sky130_fd_sc_hd__clkinv_1 _107_ (
    .A(\dpath.a_lt_b$in0[11] ),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _108_ (
    .A(\dpath.a_lt_b$in0[6] ),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _109_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _110_ (
    .A(req_rdy),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _111_ (
    .A(reset),
    .Y(_007_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _112_ (
    .A(\dpath.a_lt_b$in0[14] ),
    .SLEEP(\dpath.a_lt_b$in1[14] ),
    .X(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _113_ (
    .A(\dpath.a_lt_b$in0[14] ),
    .B(\dpath.a_lt_b$in1[14] ),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2b_1 _114_ (
    .A_N(\dpath.a_lt_b$in1[13] ),
    .B(\dpath.a_lt_b$in0[13] ),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2b_1 _115_ (
    .A_N(\dpath.a_lt_b$in0[13] ),
    .B(\dpath.a_lt_b$in1[13] ),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2b_1 _116_ (
    .A_N(\dpath.a_lt_b$in1[12] ),
    .B(\dpath.a_lt_b$in0[12] ),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _117_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B(\dpath.a_lt_b$in0[12] ),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _118_ (
    .A(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor2_1 _119_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .B(_003_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _120_ (
    .A(\dpath.a_lt_b$in1[11] ),
    .SLEEP(\dpath.a_lt_b$in0[11] ),
    .X(_016_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _121_ (
    .A(\dpath.a_lt_b$in0[10] ),
    .SLEEP(\dpath.a_lt_b$in1[10] ),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _122_ (
    .A(\dpath.a_lt_b$in1[10] ),
    .B(\dpath.a_lt_b$in0[10] ),
    .Y(_018_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _123_ (
    .A(\dpath.a_lt_b$in0[9] ),
    .SLEEP(\dpath.a_lt_b$in1[9] ),
    .X(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _124_ (
    .A(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2b_1 _125_ (
    .A_N(\dpath.a_lt_b$in0[9] ),
    .B(\dpath.a_lt_b$in1[9] ),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2b_1 _126_ (
    .A_N(\dpath.a_lt_b$in1[8] ),
    .B(\dpath.a_lt_b$in0[8] ),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xor2_1 _127_ (
    .A(\dpath.a_lt_b$in1[8] ),
    .B(\dpath.a_lt_b$in0[8] ),
    .X(_023_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _128_ (
    .A(\dpath.a_lt_b$in0[7] ),
    .SLEEP(\dpath.a_lt_b$in1[7] ),
    .X(_024_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _129_ (
    .A(\dpath.a_lt_b$in1[7] ),
    .SLEEP(\dpath.a_lt_b$in0[7] ),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _130_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B(_004_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _131_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B(\dpath.a_lt_b$in0[6] ),
    .Y(_027_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _132_ (
    .A(\dpath.a_lt_b$in0[5] ),
    .SLEEP(\dpath.a_lt_b$in1[5] ),
    .X(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _133_ (
    .A(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2b_1 _134_ (
    .A_N(\dpath.a_lt_b$in0[5] ),
    .B(\dpath.a_lt_b$in1[5] ),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2b_1 _135_ (
    .A_N(\dpath.a_lt_b$in1[4] ),
    .B(\dpath.a_lt_b$in0[4] ),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _136_ (
    .A(\dpath.a_lt_b$in1[4] ),
    .B(\dpath.a_lt_b$in0[4] ),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _138_ (
    .A(\dpath.a_lt_b$in0[3] ),
    .SLEEP(\dpath.a_lt_b$in1[3] ),
    .X(_034_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _139_ (
    .A(\dpath.a_lt_b$in1[3] ),
    .SLEEP(\dpath.a_lt_b$in0[3] ),
    .X(_035_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _140_ (
    .A(\dpath.a_lt_b$in0[2] ),
    .SLEEP(\dpath.a_lt_b$in1[2] ),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2b_1 _141_ (
    .A_N(\dpath.a_lt_b$in0[0] ),
    .B(\dpath.a_lt_b$in1[0] ),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xor2_1 _142_ (
    .A(\dpath.a_lt_b$in1[1] ),
    .B(\dpath.a_lt_b$in0[1] ),
    .X(_038_)
  );
  sky130_fd_sc_hd__maj3_1 _143_ (
    .A(_005_),
    .B(\dpath.a_lt_b$in0[1] ),
    .C(_037_),
    .X(_039_)
  );
  sky130_fd_sc_hd__xor2_1 _144_ (
    .A(\dpath.a_lt_b$in1[2] ),
    .B(\dpath.a_lt_b$in0[2] ),
    .X(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _145_ (
    .A(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a21o_1 _146_ (
    .A1(_039_),
    .A2(_041_),
    .B1(_036_),
    .X(_042_)
  );
  sky130_fd_sc_hd__a211oi_1 _147_ (
    .A1(_039_),
    .A2(_041_),
    .B1(_034_),
    .C1(_036_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__or3_1 _148_ (
    .A(_033_),
    .B(_035_),
    .C(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _149_ (
    .A(_031_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o311ai_0 _150_ (
    .A1(_033_),
    .A2(_035_),
    .A3(_043_),
    .B1(_031_),
    .C1(_029_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand3_1 _151_ (
    .A(_027_),
    .B(_030_),
    .C(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _152_ (
    .A1(\dpath.a_lt_b$in1[6] ),
    .A2(_004_),
    .B1(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a311oi_1 _153_ (
    .A1(_027_),
    .A2(_030_),
    .A3(_046_),
    .B1(_026_),
    .C1(_024_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _154_ (
    .A(_025_),
    .SLEEP(_049_),
    .X(_050_)
  );
  sky130_fd_sc_hd__o21ai_0 _155_ (
    .A1(_023_),
    .A2(_050_),
    .B1(_022_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o311ai_0 _156_ (
    .A1(_023_),
    .A2(_025_),
    .A3(_049_),
    .B1(_022_),
    .C1(_020_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _157_ (
    .A(_021_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a31oi_1 _158_ (
    .A1(_018_),
    .A2(_021_),
    .A3(_052_),
    .B1(_017_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a311oi_1 _159_ (
    .A1(_018_),
    .A2(_021_),
    .A3(_052_),
    .B1(_017_),
    .C1(_015_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__or3_1 _160_ (
    .A(_014_),
    .B(_016_),
    .C(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _161_ (
    .A(_012_),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o311ai_0 _162_ (
    .A1(_014_),
    .A2(_016_),
    .A3(_055_),
    .B1(_012_),
    .C1(_010_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__and3_1 _163_ (
    .A(_009_),
    .B(_011_),
    .C(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__a31oi_1 _164_ (
    .A1(_009_),
    .A2(_011_),
    .A3(_058_),
    .B1(_008_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _165_ (
    .A(\dpath.a_lt_b$in0[15] ),
    .SLEEP(\dpath.a_lt_b$in1[15] ),
    .X(_061_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _166_ (
    .A(\dpath.a_lt_b$in1[15] ),
    .SLEEP(\dpath.a_lt_b$in0[15] ),
    .X(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _167_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xnor2_1 _168_ (
    .A(_060_),
    .B(_063_),
    .Y(resp_msg[15])
  );
  sky130_fd_sc_hd__a21oi_1 _169_ (
    .A1(_011_),
    .A2(_058_),
    .B1(_009_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(_059_),
    .B(_064_),
    .Y(resp_msg[14])
  );
  sky130_fd_sc_hd__and2_0 _171_ (
    .A(_010_),
    .B(_011_),
    .X(_065_)
  );
  sky130_fd_sc_hd__xor2_1 _172_ (
    .A(_057_),
    .B(_065_),
    .X(resp_msg[13])
  );
  sky130_fd_sc_hd__o21ai_0 _173_ (
    .A1(_016_),
    .A2(_055_),
    .B1(_014_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__and2_0 _174_ (
    .A(_056_),
    .B(_066_),
    .X(resp_msg[12])
  );
  sky130_fd_sc_hd__nor2_1 _175_ (
    .A(_015_),
    .B(_016_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xnor2_1 _176_ (
    .A(_054_),
    .B(_067_),
    .Y(resp_msg[11])
  );
  sky130_fd_sc_hd__xnor2_1 _177_ (
    .A(_018_),
    .B(_053_),
    .Y(resp_msg[10])
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(_020_),
    .B(_021_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__xnor2_1 _179_ (
    .A(_051_),
    .B(_068_),
    .Y(resp_msg[9])
  );
  sky130_fd_sc_hd__xor2_1 _180_ (
    .A(_023_),
    .B(_050_),
    .X(resp_msg[8])
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(_024_),
    .B(_025_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__xor2_1 _182_ (
    .A(_048_),
    .B(_069_),
    .X(resp_msg[7])
  );
  sky130_fd_sc_hd__a21oi_1 _183_ (
    .A1(_030_),
    .A2(_046_),
    .B1(_027_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _184_ (
    .A(_047_),
    .SLEEP(_070_),
    .X(resp_msg[6])
  );
  sky130_fd_sc_hd__nand2_1 _185_ (
    .A(_029_),
    .B(_030_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xnor2_1 _186_ (
    .A(_045_),
    .B(_071_),
    .Y(resp_msg[5])
  );
  sky130_fd_sc_hd__o21ai_0 _187_ (
    .A1(_035_),
    .A2(_043_),
    .B1(_033_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__and2_0 _188_ (
    .A(_044_),
    .B(_072_),
    .X(resp_msg[4])
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(_034_),
    .B(_035_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__xor2_1 _190_ (
    .A(_042_),
    .B(_073_),
    .X(resp_msg[3])
  );
  sky130_fd_sc_hd__xnor2_1 _191_ (
    .A(_039_),
    .B(_040_),
    .Y(resp_msg[2])
  );
  sky130_fd_sc_hd__xnor2_1 _192_ (
    .A(_037_),
    .B(_038_),
    .Y(resp_msg[1])
  );
  sky130_fd_sc_hd__xor2_1 _193_ (
    .A(\dpath.a_lt_b$in0[0] ),
    .B(\dpath.a_lt_b$in1[0] ),
    .X(resp_msg[0])
  );
  sky130_fd_sc_hd__mux2_1 _194_ (
    .A0(\dpath.a_lt_b$in0[14] ),
    .A1(req_msg[14]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[14] )
  );
  sky130_fd_sc_hd__mux2_1 _195_ (
    .A0(\dpath.a_lt_b$in0[13] ),
    .A1(req_msg[13]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[13] )
  );
  sky130_fd_sc_hd__mux2_1 _196_ (
    .A0(\dpath.a_lt_b$in0[12] ),
    .A1(req_msg[12]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[12] )
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(req_rdy),
    .B(req_msg[11]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _198_ (
    .A1(_003_),
    .A2(req_rdy),
    .B1(_074_),
    .Y(\dpath.b_mux$out[11] )
  );
  sky130_fd_sc_hd__mux2_1 _199_ (
    .A0(\dpath.a_lt_b$in0[10] ),
    .A1(req_msg[10]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[10] )
  );
  sky130_fd_sc_hd__mux2_1 _200_ (
    .A0(\dpath.a_lt_b$in0[9] ),
    .A1(req_msg[9]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[9] )
  );
  sky130_fd_sc_hd__mux2_1 _201_ (
    .A0(\dpath.a_lt_b$in0[8] ),
    .A1(req_msg[8]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[8] )
  );
  sky130_fd_sc_hd__mux2_1 _202_ (
    .A0(\dpath.a_lt_b$in0[7] ),
    .A1(req_msg[7]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[7] )
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(req_rdy),
    .B(req_msg[6]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o21ai_0 _204_ (
    .A1(_004_),
    .A2(req_rdy),
    .B1(_075_),
    .Y(\dpath.b_mux$out[6] )
  );
  sky130_fd_sc_hd__mux2_1 _205_ (
    .A0(\dpath.a_lt_b$in0[5] ),
    .A1(req_msg[5]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[5] )
  );
  sky130_fd_sc_hd__mux2_1 _206_ (
    .A0(\dpath.a_lt_b$in0[4] ),
    .A1(req_msg[4]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[4] )
  );
  sky130_fd_sc_hd__mux2_1 _207_ (
    .A0(\dpath.a_lt_b$in0[3] ),
    .A1(req_msg[3]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[3] )
  );
  sky130_fd_sc_hd__mux2_1 _208_ (
    .A0(\dpath.a_lt_b$in0[2] ),
    .A1(req_msg[2]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[2] )
  );
  sky130_fd_sc_hd__mux2_1 _209_ (
    .A0(\dpath.a_lt_b$in0[1] ),
    .A1(req_msg[1]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[1] )
  );
  sky130_fd_sc_hd__mux2_1 _210_ (
    .A0(\dpath.a_lt_b$in0[0] ),
    .A1(req_msg[0]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[0] )
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(_006_),
    .B(\ctrl.state.out[2] ),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a311oi_1 _212_ (
    .A1(_009_),
    .A2(_011_),
    .A3(_058_),
    .B1(_061_),
    .C1(_008_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor3_1 _213_ (
    .A(req_rdy),
    .B(_062_),
    .C(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor3_1 _214_ (
    .A(_062_),
    .B(_076_),
    .C(_077_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o21ba_1 _215_ (
    .A1(_062_),
    .A2(_077_),
    .B1_N(_076_),
    .X(_080_)
  );
  sky130_fd_sc_hd__and2_0 _216_ (
    .A(req_msg[30]),
    .B(_076_),
    .X(_081_)
  );
  sky130_fd_sc_hd__a221o_1 _217_ (
    .A1(resp_msg[14]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[14] ),
    .C1(_081_),
    .X(\dpath.a_mux$out[14] )
  );
  sky130_fd_sc_hd__and2_0 _218_ (
    .A(req_msg[29]),
    .B(_076_),
    .X(_082_)
  );
  sky130_fd_sc_hd__a221o_1 _219_ (
    .A1(resp_msg[13]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[13] ),
    .C1(_082_),
    .X(\dpath.a_mux$out[13] )
  );
  sky130_fd_sc_hd__and2_0 _220_ (
    .A(req_msg[28]),
    .B(_076_),
    .X(_083_)
  );
  sky130_fd_sc_hd__a221o_1 _221_ (
    .A1(resp_msg[12]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[12] ),
    .C1(_083_),
    .X(\dpath.a_mux$out[12] )
  );
  sky130_fd_sc_hd__and2_0 _222_ (
    .A(req_msg[27]),
    .B(_076_),
    .X(_084_)
  );
  sky130_fd_sc_hd__a221o_1 _223_ (
    .A1(resp_msg[11]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[11] ),
    .C1(_084_),
    .X(\dpath.a_mux$out[11] )
  );
  sky130_fd_sc_hd__and2_0 _224_ (
    .A(req_msg[26]),
    .B(_076_),
    .X(_085_)
  );
  sky130_fd_sc_hd__a221o_1 _225_ (
    .A1(resp_msg[10]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[10] ),
    .C1(_085_),
    .X(\dpath.a_mux$out[10] )
  );
  sky130_fd_sc_hd__and2_0 _226_ (
    .A(req_msg[25]),
    .B(_076_),
    .X(_086_)
  );
  sky130_fd_sc_hd__a221o_1 _227_ (
    .A1(resp_msg[9]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[9] ),
    .C1(_086_),
    .X(\dpath.a_mux$out[9] )
  );
  sky130_fd_sc_hd__and2_0 _228_ (
    .A(req_msg[24]),
    .B(_076_),
    .X(_087_)
  );
  sky130_fd_sc_hd__a221o_1 _229_ (
    .A1(resp_msg[8]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[8] ),
    .C1(_087_),
    .X(\dpath.a_mux$out[8] )
  );
  sky130_fd_sc_hd__and2_0 _230_ (
    .A(req_msg[23]),
    .B(_076_),
    .X(_088_)
  );
  sky130_fd_sc_hd__a221o_1 _231_ (
    .A1(resp_msg[7]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[7] ),
    .C1(_088_),
    .X(\dpath.a_mux$out[7] )
  );
  sky130_fd_sc_hd__and2_0 _232_ (
    .A(req_msg[22]),
    .B(_076_),
    .X(_089_)
  );
  sky130_fd_sc_hd__a221o_1 _233_ (
    .A1(resp_msg[6]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[6] ),
    .C1(_089_),
    .X(\dpath.a_mux$out[6] )
  );
  sky130_fd_sc_hd__and2_0 _234_ (
    .A(req_msg[21]),
    .B(_076_),
    .X(_090_)
  );
  sky130_fd_sc_hd__a221o_1 _235_ (
    .A1(resp_msg[5]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[5] ),
    .C1(_090_),
    .X(\dpath.a_mux$out[5] )
  );
  sky130_fd_sc_hd__and2_0 _236_ (
    .A(req_msg[20]),
    .B(_076_),
    .X(_091_)
  );
  sky130_fd_sc_hd__a221o_1 _237_ (
    .A1(resp_msg[4]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[4] ),
    .C1(_091_),
    .X(\dpath.a_mux$out[4] )
  );
  sky130_fd_sc_hd__and2_0 _238_ (
    .A(req_msg[19]),
    .B(_076_),
    .X(_092_)
  );
  sky130_fd_sc_hd__a221o_1 _239_ (
    .A1(resp_msg[3]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[3] ),
    .C1(_092_),
    .X(\dpath.a_mux$out[3] )
  );
  sky130_fd_sc_hd__and2_0 _240_ (
    .A(req_msg[18]),
    .B(_076_),
    .X(_093_)
  );
  sky130_fd_sc_hd__a221o_1 _241_ (
    .A1(resp_msg[2]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[2] ),
    .C1(_093_),
    .X(\dpath.a_mux$out[2] )
  );
  sky130_fd_sc_hd__and2_0 _242_ (
    .A(req_msg[17]),
    .B(_076_),
    .X(_094_)
  );
  sky130_fd_sc_hd__a221o_1 _243_ (
    .A1(resp_msg[1]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[1] ),
    .C1(_094_),
    .X(\dpath.a_mux$out[1] )
  );
  sky130_fd_sc_hd__and2_0 _244_ (
    .A(req_msg[16]),
    .B(_076_),
    .X(_095_)
  );
  sky130_fd_sc_hd__a221o_1 _245_ (
    .A1(resp_msg[0]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[0] ),
    .C1(_095_),
    .X(\dpath.a_mux$out[0] )
  );
  sky130_fd_sc_hd__nor2_1 _246_ (
    .A(req_rdy),
    .B(\ctrl.state.out[2] ),
    .Y(_096_)
  );
  sky130_fd_sc_hd__clkinv_1 _247_ (
    .A(_096_),
    .Y(\ctrl$a_reg_en[0] )
  );
  sky130_fd_sc_hd__and2_0 _248_ (
    .A(\ctrl.state.out[1] ),
    .B(_096_),
    .X(resp_val)
  );
  sky130_fd_sc_hd__a21oi_1 _249_ (
    .A1(resp_rdy),
    .A2(resp_val),
    .B1(reset),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21ai_0 _250_ (
    .A1(_006_),
    .A2(req_val),
    .B1(_097_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__and2_0 _251_ (
    .A(req_msg[31]),
    .B(_076_),
    .X(_098_)
  );
  sky130_fd_sc_hd__a221o_1 _252_ (
    .A1(resp_msg[15]),
    .A2(_079_),
    .B1(_080_),
    .B2(\dpath.a_lt_b$in1[15] ),
    .C1(_098_),
    .X(\dpath.a_mux$out[15] )
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(\dpath.a_lt_b$in0[15] ),
    .A1(req_msg[15]),
    .S(req_rdy),
    .X(\dpath.b_mux$out[15] )
  );
  sky130_fd_sc_hd__nor2_1 _254_ (
    .A(_078_),
    .B(_096_),
    .Y(\ctrl$b_reg_en[0] )
  );
  sky130_fd_sc_hd__nor2_1 _255_ (
    .A(\dpath.a_lt_b$in1[12] ),
    .B(\dpath.a_lt_b$in1[10] ),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor4_1 _256_ (
    .A(\dpath.a_lt_b$in1[13] ),
    .B(\dpath.a_lt_b$in1[9] ),
    .C(\dpath.a_lt_b$in1[8] ),
    .D(\dpath.a_lt_b$in1[7] ),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor4_1 _257_ (
    .A(\dpath.a_lt_b$in1[14] ),
    .B(\dpath.a_lt_b$in1[11] ),
    .C(\dpath.a_lt_b$in1[5] ),
    .D(\dpath.a_lt_b$in1[4] ),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand3_1 _258_ (
    .A(_099_),
    .B(_100_),
    .C(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__or4_1 _259_ (
    .A(\dpath.a_lt_b$in1[6] ),
    .B(\dpath.a_lt_b$in1[3] ),
    .C(\dpath.a_lt_b$in1[2] ),
    .D(\dpath.a_lt_b$in1[1] ),
    .X(_103_)
  );
  sky130_fd_sc_hd__nor4_1 _260_ (
    .A(\dpath.a_lt_b$in1[0] ),
    .B(\dpath.a_lt_b$in1[15] ),
    .C(_102_),
    .D(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(\ctrl.state.out[2] ),
    .B(_007_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a32o_1 _262_ (
    .A1(\ctrl.state.out[2] ),
    .A2(_007_),
    .A3(_104_),
    .B1(_097_),
    .B2(\ctrl.state.out[1] ),
    .X(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(req_rdy),
    .B(req_val),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o22ai_1 _264_ (
    .A1(_104_),
    .A2(_105_),
    .B1(_106_),
    .B2(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__edfxtp_1 _265_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[0] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[0] )
  );
  sky130_fd_sc_hd__edfxtp_1 _266_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[1] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[1] )
  );
  sky130_fd_sc_hd__edfxtp_1 _267_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[2] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[2] )
  );
  sky130_fd_sc_hd__edfxtp_1 _268_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[3] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[3] )
  );
  sky130_fd_sc_hd__edfxtp_1 _269_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[4] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[4] )
  );
  sky130_fd_sc_hd__edfxtp_1 _270_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[5] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[5] )
  );
  sky130_fd_sc_hd__edfxtp_1 _271_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[6] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[6] )
  );
  sky130_fd_sc_hd__edfxtp_1 _272_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[7] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[7] )
  );
  sky130_fd_sc_hd__edfxtp_1 _273_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[8] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[8] )
  );
  sky130_fd_sc_hd__edfxtp_1 _274_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[9] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[9] )
  );
  sky130_fd_sc_hd__edfxtp_1 _275_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[10] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[10] )
  );
  sky130_fd_sc_hd__edfxtp_1 _276_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[11] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[11] )
  );
  sky130_fd_sc_hd__edfxtp_1 _277_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[12] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[12] )
  );
  sky130_fd_sc_hd__edfxtp_1 _278_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[13] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[13] )
  );
  sky130_fd_sc_hd__edfxtp_1 _279_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[14] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[14] )
  );
  sky130_fd_sc_hd__edfxtp_1 _280_ (
    .CLK(clk),
    .D(\dpath.a_mux$out[15] ),
    .DE(\ctrl$a_reg_en[0] ),
    .Q(\dpath.a_lt_b$in0[15] )
  );
  sky130_fd_sc_hd__edfxtp_1 _281_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[0] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[0] )
  );
  sky130_fd_sc_hd__edfxtp_1 _282_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[1] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[1] )
  );
  sky130_fd_sc_hd__edfxtp_1 _283_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[2] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[2] )
  );
  sky130_fd_sc_hd__edfxtp_1 _284_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[3] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[3] )
  );
  sky130_fd_sc_hd__edfxtp_1 _285_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[4] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[4] )
  );
  sky130_fd_sc_hd__edfxtp_1 _286_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[5] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[5] )
  );
  sky130_fd_sc_hd__edfxtp_1 _287_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[6] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[6] )
  );
  sky130_fd_sc_hd__edfxtp_1 _288_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[7] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[7] )
  );
  sky130_fd_sc_hd__edfxtp_1 _289_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[8] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[8] )
  );
  sky130_fd_sc_hd__edfxtp_1 _290_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[9] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[9] )
  );
  sky130_fd_sc_hd__edfxtp_1 _291_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[10] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[10] )
  );
  sky130_fd_sc_hd__edfxtp_1 _292_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[11] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[11] )
  );
  sky130_fd_sc_hd__edfxtp_1 _293_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[12] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[12] )
  );
  sky130_fd_sc_hd__edfxtp_1 _294_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[13] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[13] )
  );
  sky130_fd_sc_hd__edfxtp_1 _295_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[14] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[14] )
  );
  sky130_fd_sc_hd__edfxtp_1 _296_ (
    .CLK(clk),
    .D(\dpath.b_mux$out[15] ),
    .DE(\ctrl$b_reg_en[0] ),
    .Q(\dpath.a_lt_b$in1[15] )
  );
  sky130_fd_sc_hd__dfxtp_1 _297_ (
    .CLK(clk),
    .D(_000_),
    .Q(req_rdy)
  );
  sky130_fd_sc_hd__dfxtp_1 _298_ (
    .CLK(clk),
    .D(_001_),
    .Q(\ctrl.state.out[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _299_ (
    .CLK(clk),
    .D(_002_),
    .Q(\ctrl.state.out[2] )
  );
endmodule
