`include "VX_define.vh"
// Flat-port wrapper around VX_execute so sv2v can flatten its interface ports.
// Generated by gen_wrapper.py --num-ex-units 3 --issue-width 1 --num-lsu-blocks 1 --num-alu-blocks 1
module exec_top import VX_gpu_pkg::*; #(
    parameter CORE_ID = 0
) (
    input  wire clk,
    input  wire reset,
    output wire lsu_client_if_0_req_valid,
    output wire [$bits(lsu_req_data_t)-1:0] lsu_client_if_0_req_data,
    input  wire lsu_client_if_0_req_ready,
    input  wire lsu_client_if_0_rsp_valid,
    input  wire [$bits(lsu_rsp_data_t)-1:0] lsu_client_if_0_rsp_data,
    output wire lsu_client_if_0_rsp_ready,
    input  wire dispatch_if_0_valid,
    input  wire [$bits(dispatch_t)-1:0] dispatch_if_0_data,
    output wire dispatch_if_0_ready,
    input  wire dispatch_if_1_valid,
    input  wire [$bits(dispatch_t)-1:0] dispatch_if_1_data,
    output wire dispatch_if_1_ready,
    input  wire dispatch_if_2_valid,
    input  wire [$bits(dispatch_t)-1:0] dispatch_if_2_data,
    output wire dispatch_if_2_ready,
    output wire commit_if_0_valid,
    output wire [$bits(commit_t)-1:0] commit_if_0_data,
    input  wire commit_if_0_ready,
    output wire commit_if_1_valid,
    output wire [$bits(commit_t)-1:0] commit_if_1_data,
    input  wire commit_if_1_ready,
    output wire commit_if_2_valid,
    output wire [$bits(commit_t)-1:0] commit_if_2_data,
    input  wire commit_if_2_ready,
    input  wire [PERF_CTR_BITS-1:0] sched_csr_if_cycles,
    input  wire [PERF_CTR_BITS-1:0] sched_csr_if_instret,
    input  wire [`VX_CFG_NUM_WARPS-1:0] sched_csr_if_active_warps,
    input  wire [`VX_CFG_NUM_WARPS*`VX_CFG_NUM_THREADS-1:0] sched_csr_if_thread_masks,
    input  wire [`VX_CFG_MEM_ADDR_WIDTH-1:0] sched_csr_if_mscratch,
    input  wire [$bits(cta_csrs_t)-1:0] sched_csr_if_cta_csrs,
    input  wire [`VX_CFG_NUM_THREADS*$bits(cta_lane_t)-1:0] sched_csr_if_cta_lane,
    input  wire [`VX_CFG_XLEN-1:0] sched_csr_if_csr_mstatus,
    input  wire [`VX_CFG_XLEN-1:0] sched_csr_if_csr_mtvec,
    input  wire [`VX_CFG_XLEN-1:0] sched_csr_if_csr_mepc,
    input  wire [`VX_CFG_XLEN-1:0] sched_csr_if_csr_mcause,
    input  wire [`VX_CFG_XLEN-1:0] sched_csr_if_csr_mtval,
    output wire [NW_WIDTH-1:0] sched_csr_if_csr_rd_wid,
    output wire [NCTA_WIDTH-1:0] sched_csr_if_csr_rd_cta_id,
    output wire sched_csr_if_csr_wr_valid,
    output wire [NW_WIDTH-1:0] sched_csr_if_csr_wr_wid,
    output wire [`VX_CFG_MEM_ADDR_WIDTH-1:0] sched_csr_if_csr_wr_data,
    output wire sched_csr_if_trap_csr_wr_valid,
    output wire [`VX_CSR_ADDR_BITS-1:0] sched_csr_if_trap_csr_wr_addr,
    output wire [`VX_CFG_XLEN-1:0] sched_csr_if_trap_csr_wr_data,
    output wire branch_ctl_if_0_valid,
    output wire [NW_WIDTH-1:0] branch_ctl_if_0_wid,
    output wire branch_ctl_if_0_taken,
    output wire [PC_BITS-1:0] branch_ctl_if_0_dest,
    output wire branch_ctl_if_0_is_trap,
    output wire branch_ctl_if_0_is_mret,
    output wire [4-1:0] branch_ctl_if_0_trap_cause,
    output wire warp_ctl_if_wspawn_valid,
    output wire warp_ctl_if_tmc_valid,
    output wire warp_ctl_if_split_valid,
    output wire warp_ctl_if_sjoin_valid,
    output wire warp_ctl_if_bar_valid,
    output wire warp_ctl_if_wsync_valid,
    output wire [NW_WIDTH-1:0] warp_ctl_if_wid,
    output wire [$bits(wspawn_t)-1:0] warp_ctl_if_wspawn,
    output wire [$bits(tmc_t)-1:0] warp_ctl_if_tmc,
    output wire [$bits(split_t)-1:0] warp_ctl_if_split,
    output wire [$bits(join_t)-1:0] warp_ctl_if_sjoin,
    output wire [$bits(barrier_t)-1:0] warp_ctl_if_bar,
    output wire [BAR_ADDR_W-1:0] warp_ctl_if_bar_addr,
    output wire [NW_WIDTH-1:0] warp_ctl_if_dvstack_wid,
    input  wire warp_ctl_if_bar_phase,
    input  wire [`VX_CFG_NUM_WARPS-1:0] warp_ctl_if_warp_pending_alm_empty,
    input  wire warp_ctl_if_lsu_sched_drained,
    input  wire [DV_STACK_SIZEW-1:0] warp_ctl_if_dvstack_ptr,
    input  wire dcr_csr_if_valid,
    input  wire [`VX_CSR_ADDR_BITS-1:0] dcr_csr_if_addr,
    input  wire [8-1:0] dcr_csr_if_mpm_class,
    output wire [VX_DCR_DATA_WIDTH-1:0] dcr_csr_if_value,
    output wire dcr_csr_if_ready
);

    // guard: the numeric counts baked into the port names must match the package
    if (NUM_EX_UNITS * `VX_CFG_ISSUE_WIDTH != 3) begin : g_chk_disp
        $error("exec_top: regenerate with --num-ex-units/--issue-width");
    end
    if (`VX_CFG_NUM_LSU_BLOCKS != 1) begin : g_chk_lsu
        $error("exec_top: regenerate with --num-lsu-blocks");
    end
    if (`VX_CFG_NUM_ALU_BLOCKS != 1) begin : g_chk_alu
        $error("exec_top: regenerate with --num-alu-blocks");
    end

    VX_lsu_sched_if lsu_client_if[`VX_CFG_NUM_LSU_BLOCKS]();
    VX_dispatch_if dispatch_if[NUM_EX_UNITS * `VX_CFG_ISSUE_WIDTH]();
    VX_commit_if commit_if[NUM_EX_UNITS * `VX_CFG_ISSUE_WIDTH]();
    VX_sched_csr_if sched_csr_if();
    VX_branch_ctl_if branch_ctl_if[`VX_CFG_NUM_ALU_BLOCKS]();
    VX_warp_ctl_if warp_ctl_if();
    VX_dcr_csr_if dcr_csr_if();

    assign lsu_client_if_0_req_valid = lsu_client_if[0].req_valid;
    assign lsu_client_if_0_req_data = lsu_client_if[0].req_data;
    assign lsu_client_if[0].req_ready = lsu_client_if_0_req_ready;
    assign lsu_client_if[0].rsp_valid = lsu_client_if_0_rsp_valid;
    assign lsu_client_if[0].rsp_data = lsu_rsp_data_t'(lsu_client_if_0_rsp_data);
    assign lsu_client_if_0_rsp_ready = lsu_client_if[0].rsp_ready;
    assign dispatch_if[0].valid = dispatch_if_0_valid;
    assign dispatch_if[0].data = dispatch_t'(dispatch_if_0_data);
    assign dispatch_if_0_ready = dispatch_if[0].ready;
    assign dispatch_if[1].valid = dispatch_if_1_valid;
    assign dispatch_if[1].data = dispatch_t'(dispatch_if_1_data);
    assign dispatch_if_1_ready = dispatch_if[1].ready;
    assign dispatch_if[2].valid = dispatch_if_2_valid;
    assign dispatch_if[2].data = dispatch_t'(dispatch_if_2_data);
    assign dispatch_if_2_ready = dispatch_if[2].ready;
    assign commit_if_0_valid = commit_if[0].valid;
    assign commit_if_0_data = commit_if[0].data;
    assign commit_if[0].ready = commit_if_0_ready;
    assign commit_if_1_valid = commit_if[1].valid;
    assign commit_if_1_data = commit_if[1].data;
    assign commit_if[1].ready = commit_if_1_ready;
    assign commit_if_2_valid = commit_if[2].valid;
    assign commit_if_2_data = commit_if[2].data;
    assign commit_if[2].ready = commit_if_2_ready;
    assign sched_csr_if.cycles = sched_csr_if_cycles;
    assign sched_csr_if.instret = sched_csr_if_instret;
    assign sched_csr_if.active_warps = sched_csr_if_active_warps;
    assign sched_csr_if.thread_masks = sched_csr_if_thread_masks;
    assign sched_csr_if.mscratch = sched_csr_if_mscratch;
    assign sched_csr_if.cta_csrs = cta_csrs_t'(sched_csr_if_cta_csrs);
    assign sched_csr_if.cta_lane = sched_csr_if_cta_lane;
    assign sched_csr_if.csr_mstatus = sched_csr_if_csr_mstatus;
    assign sched_csr_if.csr_mtvec = sched_csr_if_csr_mtvec;
    assign sched_csr_if.csr_mepc = sched_csr_if_csr_mepc;
    assign sched_csr_if.csr_mcause = sched_csr_if_csr_mcause;
    assign sched_csr_if.csr_mtval = sched_csr_if_csr_mtval;
    assign sched_csr_if_csr_rd_wid = sched_csr_if.csr_rd_wid;
    assign sched_csr_if_csr_rd_cta_id = sched_csr_if.csr_rd_cta_id;
    assign sched_csr_if_csr_wr_valid = sched_csr_if.csr_wr_valid;
    assign sched_csr_if_csr_wr_wid = sched_csr_if.csr_wr_wid;
    assign sched_csr_if_csr_wr_data = sched_csr_if.csr_wr_data;
    assign sched_csr_if_trap_csr_wr_valid = sched_csr_if.trap_csr_wr_valid;
    assign sched_csr_if_trap_csr_wr_addr = sched_csr_if.trap_csr_wr_addr;
    assign sched_csr_if_trap_csr_wr_data = sched_csr_if.trap_csr_wr_data;
    assign branch_ctl_if_0_valid = branch_ctl_if[0].valid;
    assign branch_ctl_if_0_wid = branch_ctl_if[0].wid;
    assign branch_ctl_if_0_taken = branch_ctl_if[0].taken;
    assign branch_ctl_if_0_dest = branch_ctl_if[0].dest;
    assign branch_ctl_if_0_is_trap = branch_ctl_if[0].is_trap;
    assign branch_ctl_if_0_is_mret = branch_ctl_if[0].is_mret;
    assign branch_ctl_if_0_trap_cause = branch_ctl_if[0].trap_cause;
    assign warp_ctl_if_wspawn_valid = warp_ctl_if.wspawn_valid;
    assign warp_ctl_if_tmc_valid = warp_ctl_if.tmc_valid;
    assign warp_ctl_if_split_valid = warp_ctl_if.split_valid;
    assign warp_ctl_if_sjoin_valid = warp_ctl_if.sjoin_valid;
    assign warp_ctl_if_bar_valid = warp_ctl_if.bar_valid;
    assign warp_ctl_if_wsync_valid = warp_ctl_if.wsync_valid;
    assign warp_ctl_if_wid = warp_ctl_if.wid;
    assign warp_ctl_if_wspawn = warp_ctl_if.wspawn;
    assign warp_ctl_if_tmc = warp_ctl_if.tmc;
    assign warp_ctl_if_split = warp_ctl_if.split;
    assign warp_ctl_if_sjoin = warp_ctl_if.sjoin;
    assign warp_ctl_if_bar = warp_ctl_if.bar;
    assign warp_ctl_if_bar_addr = warp_ctl_if.bar_addr;
    assign warp_ctl_if_dvstack_wid = warp_ctl_if.dvstack_wid;
    assign warp_ctl_if.bar_phase = warp_ctl_if_bar_phase;
    assign warp_ctl_if.warp_pending_alm_empty = warp_ctl_if_warp_pending_alm_empty;
    assign warp_ctl_if.lsu_sched_drained = warp_ctl_if_lsu_sched_drained;
    assign warp_ctl_if.dvstack_ptr = warp_ctl_if_dvstack_ptr;
    assign dcr_csr_if.valid = dcr_csr_if_valid;
    assign dcr_csr_if.addr = dcr_csr_if_addr;
    assign dcr_csr_if.mpm_class = dcr_csr_if_mpm_class;
    assign dcr_csr_if_value = dcr_csr_if.value;
    assign dcr_csr_if_ready = dcr_csr_if.ready;

    VX_execute #(
        .INSTANCE_ID ("exec0"),
        .CORE_ID     (CORE_ID)
    ) execute (
        .clk           (clk),
        .reset         (reset),
        .lsu_client_if (lsu_client_if),
        .dispatch_if   (dispatch_if),
        .commit_if     (commit_if),
        .sched_csr_if  (sched_csr_if),
        .branch_ctl_if (branch_ctl_if),
        .warp_ctl_if   (warp_ctl_if),
        .dcr_csr_if    (dcr_csr_if)
    );
endmodule
