-- NVC replay bench for exec_top (VX_execute, Tier B): re-applies every
-- cycle's recorded inputs from vectors.txt (written by the vvp oracle
-- tb_exec.sv) at the falling clock edge and compares every output 1 ns
-- later, from cycle 0.  An 'X' in an expected bit is a don't-care; the
-- handshake expectations (every *_valid / *_ready output) are required to be
-- defined once reset is released so the compare cannot be vacuous.
-- Pre-history matches the oracle exactly: reset starts asserted, row 0's
-- inputs are driven from time 0 (the oracle's initial values), the first
-- rising edge is at 5 ns and row k is sampled by the edge at 5 + 10k ns.
-- GENERATED by gen_tb.py from ports_tierB.txt -- do not edit by hand.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;
library sv2vhdl;
use sv2vhdl.logic3d_types_pkg.all;

entity tb_exec_replay is end entity;

architecture t of tb_exec_replay is
    signal clk : logic3d := L3D_0;
    signal running : boolean := true;

    signal reset : logic3d := L3D_1;
    signal lsu_client_if_0_req_valid : logic3d;
    signal lsu_client_if_0_req_data : logic3d_vector(221 downto 0);
    signal lsu_client_if_0_req_ready : logic3d := L3D_0;
    signal lsu_client_if_0_rsp_valid : logic3d := L3D_0;
    signal lsu_client_if_0_rsp_data : logic3d_vector(130 downto 0) := (others => L3D_0);
    signal lsu_client_if_0_rsp_ready : logic3d;
    signal dispatch_if_0_valid : logic3d := L3D_0;
    signal dispatch_if_0_data : logic3d_vector(273 downto 0) := (others => L3D_0);
    signal dispatch_if_0_ready : logic3d;
    signal dispatch_if_1_valid : logic3d := L3D_0;
    signal dispatch_if_1_data : logic3d_vector(273 downto 0) := (others => L3D_0);
    signal dispatch_if_1_ready : logic3d;
    signal dispatch_if_2_valid : logic3d := L3D_0;
    signal dispatch_if_2_data : logic3d_vector(273 downto 0) := (others => L3D_0);
    signal dispatch_if_2_ready : logic3d;
    signal dispatch_if_3_valid : logic3d := L3D_0;
    signal dispatch_if_3_data : logic3d_vector(273 downto 0) := (others => L3D_0);
    signal dispatch_if_3_ready : logic3d;
    signal commit_if_0_valid : logic3d;
    signal commit_if_0_data : logic3d_vector(114 downto 0);
    signal commit_if_0_ready : logic3d := L3D_0;
    signal commit_if_1_valid : logic3d;
    signal commit_if_1_data : logic3d_vector(114 downto 0);
    signal commit_if_1_ready : logic3d := L3D_0;
    signal commit_if_2_valid : logic3d;
    signal commit_if_2_data : logic3d_vector(114 downto 0);
    signal commit_if_2_ready : logic3d := L3D_0;
    signal commit_if_3_valid : logic3d;
    signal commit_if_3_data : logic3d_vector(114 downto 0);
    signal commit_if_3_ready : logic3d := L3D_0;
    signal sched_csr_if_cycles : logic3d_vector(43 downto 0) := (others => L3D_0);
    signal sched_csr_if_instret : logic3d_vector(43 downto 0) := (others => L3D_0);
    signal sched_csr_if_active_warps : logic3d_vector(1 downto 0) := (others => L3D_0);
    signal sched_csr_if_thread_masks : logic3d_vector(3 downto 0) := (others => L3D_0);
    signal sched_csr_if_mscratch : logic3d_vector(31 downto 0) := (others => L3D_0);
    signal sched_csr_if_cta_csrs : logic3d_vector(330 downto 0) := (others => L3D_0);
    signal sched_csr_if_cta_lane : logic3d_vector(11 downto 0) := (others => L3D_0);
    signal sched_csr_if_csr_mstatus : logic3d_vector(31 downto 0) := (others => L3D_0);
    signal sched_csr_if_csr_mtvec : logic3d_vector(31 downto 0) := (others => L3D_0);
    signal sched_csr_if_csr_mepc : logic3d_vector(31 downto 0) := (others => L3D_0);
    signal sched_csr_if_csr_mcause : logic3d_vector(31 downto 0) := (others => L3D_0);
    signal sched_csr_if_csr_mtval : logic3d_vector(31 downto 0) := (others => L3D_0);
    signal sched_csr_if_csr_rd_wid : logic3d;
    signal sched_csr_if_csr_rd_cta_id : logic3d;
    signal sched_csr_if_csr_wr_valid : logic3d;
    signal sched_csr_if_csr_wr_wid : logic3d;
    signal sched_csr_if_csr_wr_data : logic3d_vector(31 downto 0);
    signal sched_csr_if_trap_csr_wr_valid : logic3d;
    signal sched_csr_if_trap_csr_wr_addr : logic3d_vector(11 downto 0);
    signal sched_csr_if_trap_csr_wr_data : logic3d_vector(31 downto 0);
    signal branch_ctl_if_0_valid : logic3d;
    signal branch_ctl_if_0_wid : logic3d;
    signal branch_ctl_if_0_taken : logic3d;
    signal branch_ctl_if_0_dest : logic3d_vector(29 downto 0);
    signal branch_ctl_if_0_is_trap : logic3d;
    signal branch_ctl_if_0_is_mret : logic3d;
    signal branch_ctl_if_0_trap_cause : logic3d_vector(3 downto 0);
    signal warp_ctl_if_wspawn_valid : logic3d;
    signal warp_ctl_if_tmc_valid : logic3d;
    signal warp_ctl_if_split_valid : logic3d;
    signal warp_ctl_if_sjoin_valid : logic3d;
    signal warp_ctl_if_bar_valid : logic3d;
    signal warp_ctl_if_wsync_valid : logic3d;
    signal warp_ctl_if_wid : logic3d;
    signal warp_ctl_if_wspawn : logic3d_vector(31 downto 0);
    signal warp_ctl_if_tmc : logic3d_vector(1 downto 0);
    signal warp_ctl_if_split : logic3d_vector(34 downto 0);
    signal warp_ctl_if_sjoin : logic3d_vector(2 downto 0);
    signal warp_ctl_if_bar : logic3d_vector(12 downto 0);
    signal warp_ctl_if_bar_addr : logic3d_vector(3 downto 0);
    signal warp_ctl_if_dvstack_wid : logic3d;
    signal warp_ctl_if_bar_phase : logic3d := L3D_0;
    signal warp_ctl_if_warp_pending_alm_empty : logic3d_vector(1 downto 0) := (others => L3D_0);
    signal warp_ctl_if_lsu_sched_drained : logic3d := L3D_0;
    signal warp_ctl_if_dvstack_ptr : logic3d := L3D_0;
    signal dcr_csr_if_valid : logic3d := L3D_0;
    signal dcr_csr_if_addr : logic3d_vector(11 downto 0) := (others => L3D_0);
    signal dcr_csr_if_mpm_class : logic3d_vector(7 downto 0) := (others => L3D_0);
    signal dcr_csr_if_value : logic3d_vector(31 downto 0);
    signal dcr_csr_if_ready : logic3d;

    -- expected bit 'X' (vvp printed x) is a don't-care
    function matches(act, exp : std_logic_vector) return boolean is
        alias a : std_logic_vector(act'length-1 downto 0) is act;
        alias e : std_logic_vector(exp'length-1 downto 0) is exp;
    begin
        for i in a'range loop
            if e(i) /= 'X' and e(i) /= 'U' and a(i) /= e(i) then return false; end if;
        end loop;
        return true;
    end function;

    -- lossless std_logic_vector -> logic3d_vector (keeps X/Z)
    function slv2l3d(s : std_logic_vector) return logic3d_vector is
        alias a : std_logic_vector(s'length-1 downto 0) is s;
        variable r : logic3d_vector(s'length-1 downto 0);
    begin
        for i in a'range loop r(i) := to_logic3d(a(i)); end loop;
        return r;
    end function;

    -- read one nibble-padded hex token as vvp's %h prints it: 0-9 a-f A-F,
    -- and x/X (all- or part-unknown nibble) / z/Z, which IEEE HREAD rejects
    -- (and then leaves the line pointer mid-token).
    -- v'length/4 characters are consumed after skipping blanks.
    procedure rdhex(l : inout line; v : out std_logic_vector) is
        alias a : std_logic_vector(v'length-1 downto 0) is v;
        variable c : character;
        variable ok : boolean;
        variable nib : std_logic_vector(3 downto 0);
    begin
        loop
            read(l, c, ok);
            assert ok report "vectors.txt: short line" severity failure;
            exit when c /= ' ' and c /= HT;
        end loop;
        for i in v'length/4 - 1 downto 0 loop
            case c is
                when '0' => nib := x"0"; when '1' => nib := x"1"; when '2' => nib := x"2"; when '3' => nib := x"3";
                when '4' => nib := x"4"; when '5' => nib := x"5"; when '6' => nib := x"6"; when '7' => nib := x"7";
                when '8' => nib := x"8"; when '9' => nib := x"9";
                when 'a' | 'A' => nib := x"A"; when 'b' | 'B' => nib := x"B"; when 'c' | 'C' => nib := x"C";
                when 'd' | 'D' => nib := x"D"; when 'e' | 'E' => nib := x"E"; when 'f' | 'F' => nib := x"F";
                when 'x' | 'X' => nib := "XXXX";
                when 'z' | 'Z' => nib := "ZZZZ";
                when others => assert false report "vectors.txt: bad hex char '" & c & "'" severity failure;
            end case;
            a(i*4+3 downto i*4) := nib;
            if i > 0 then
                read(l, c, ok);
                assert ok report "vectors.txt: short token" severity failure;
            end if;
        end loop;
    end procedure;

    -- read one binary token as vvp's %b prints it: exactly one character
    -- per bit (0/1/x/z), so an x bit is a don't-care for that bit only.
    procedure rdbin(l : inout line; v : out std_logic_vector) is
        alias a : std_logic_vector(v'length-1 downto 0) is v;
        variable c : character;
        variable ok : boolean;
    begin
        loop
            read(l, c, ok);
            assert ok report "vectors.txt: short line" severity failure;
            exit when c /= ' ' and c /= HT;
        end loop;
        for i in v'length - 1 downto 0 loop
            case c is
                when '0' => a(i) := '0'; when '1' => a(i) := '1';
                when 'x' | 'X' => a(i) := 'X'; when 'z' | 'Z' => a(i) := 'Z';
                when others => assert false report "vectors.txt: bad bin char '" & c & "'" severity failure;
            end case;
            if i > 0 then
                read(l, c, ok);
                assert ok report "vectors.txt: short token" severity failure;
            end if;
        end loop;
    end procedure;
begin
    dut: entity work.exec_top
        port map (
            clk => clk,
            reset => reset,
            lsu_client_if_0_req_valid => lsu_client_if_0_req_valid,
            lsu_client_if_0_req_data => lsu_client_if_0_req_data,
            lsu_client_if_0_req_ready => lsu_client_if_0_req_ready,
            lsu_client_if_0_rsp_valid => lsu_client_if_0_rsp_valid,
            lsu_client_if_0_rsp_data => lsu_client_if_0_rsp_data,
            lsu_client_if_0_rsp_ready => lsu_client_if_0_rsp_ready,
            dispatch_if_0_valid => dispatch_if_0_valid,
            dispatch_if_0_data => dispatch_if_0_data,
            dispatch_if_0_ready => dispatch_if_0_ready,
            dispatch_if_1_valid => dispatch_if_1_valid,
            dispatch_if_1_data => dispatch_if_1_data,
            dispatch_if_1_ready => dispatch_if_1_ready,
            dispatch_if_2_valid => dispatch_if_2_valid,
            dispatch_if_2_data => dispatch_if_2_data,
            dispatch_if_2_ready => dispatch_if_2_ready,
            dispatch_if_3_valid => dispatch_if_3_valid,
            dispatch_if_3_data => dispatch_if_3_data,
            dispatch_if_3_ready => dispatch_if_3_ready,
            commit_if_0_valid => commit_if_0_valid,
            commit_if_0_data => commit_if_0_data,
            commit_if_0_ready => commit_if_0_ready,
            commit_if_1_valid => commit_if_1_valid,
            commit_if_1_data => commit_if_1_data,
            commit_if_1_ready => commit_if_1_ready,
            commit_if_2_valid => commit_if_2_valid,
            commit_if_2_data => commit_if_2_data,
            commit_if_2_ready => commit_if_2_ready,
            commit_if_3_valid => commit_if_3_valid,
            commit_if_3_data => commit_if_3_data,
            commit_if_3_ready => commit_if_3_ready,
            sched_csr_if_cycles => sched_csr_if_cycles,
            sched_csr_if_instret => sched_csr_if_instret,
            sched_csr_if_active_warps => sched_csr_if_active_warps,
            sched_csr_if_thread_masks => sched_csr_if_thread_masks,
            sched_csr_if_mscratch => sched_csr_if_mscratch,
            sched_csr_if_cta_csrs => sched_csr_if_cta_csrs,
            sched_csr_if_cta_lane => sched_csr_if_cta_lane,
            sched_csr_if_csr_mstatus => sched_csr_if_csr_mstatus,
            sched_csr_if_csr_mtvec => sched_csr_if_csr_mtvec,
            sched_csr_if_csr_mepc => sched_csr_if_csr_mepc,
            sched_csr_if_csr_mcause => sched_csr_if_csr_mcause,
            sched_csr_if_csr_mtval => sched_csr_if_csr_mtval,
            sched_csr_if_csr_rd_wid => sched_csr_if_csr_rd_wid,
            sched_csr_if_csr_rd_cta_id => sched_csr_if_csr_rd_cta_id,
            sched_csr_if_csr_wr_valid => sched_csr_if_csr_wr_valid,
            sched_csr_if_csr_wr_wid => sched_csr_if_csr_wr_wid,
            sched_csr_if_csr_wr_data => sched_csr_if_csr_wr_data,
            sched_csr_if_trap_csr_wr_valid => sched_csr_if_trap_csr_wr_valid,
            sched_csr_if_trap_csr_wr_addr => sched_csr_if_trap_csr_wr_addr,
            sched_csr_if_trap_csr_wr_data => sched_csr_if_trap_csr_wr_data,
            branch_ctl_if_0_valid => branch_ctl_if_0_valid,
            branch_ctl_if_0_wid => branch_ctl_if_0_wid,
            branch_ctl_if_0_taken => branch_ctl_if_0_taken,
            branch_ctl_if_0_dest => branch_ctl_if_0_dest,
            branch_ctl_if_0_is_trap => branch_ctl_if_0_is_trap,
            branch_ctl_if_0_is_mret => branch_ctl_if_0_is_mret,
            branch_ctl_if_0_trap_cause => branch_ctl_if_0_trap_cause,
            warp_ctl_if_wspawn_valid => warp_ctl_if_wspawn_valid,
            warp_ctl_if_tmc_valid => warp_ctl_if_tmc_valid,
            warp_ctl_if_split_valid => warp_ctl_if_split_valid,
            warp_ctl_if_sjoin_valid => warp_ctl_if_sjoin_valid,
            warp_ctl_if_bar_valid => warp_ctl_if_bar_valid,
            warp_ctl_if_wsync_valid => warp_ctl_if_wsync_valid,
            warp_ctl_if_wid => warp_ctl_if_wid,
            warp_ctl_if_wspawn => warp_ctl_if_wspawn,
            warp_ctl_if_tmc => warp_ctl_if_tmc,
            warp_ctl_if_split => warp_ctl_if_split,
            warp_ctl_if_sjoin => warp_ctl_if_sjoin,
            warp_ctl_if_bar => warp_ctl_if_bar,
            warp_ctl_if_bar_addr => warp_ctl_if_bar_addr,
            warp_ctl_if_dvstack_wid => warp_ctl_if_dvstack_wid,
            warp_ctl_if_bar_phase => warp_ctl_if_bar_phase,
            warp_ctl_if_warp_pending_alm_empty => warp_ctl_if_warp_pending_alm_empty,
            warp_ctl_if_lsu_sched_drained => warp_ctl_if_lsu_sched_drained,
            warp_ctl_if_dvstack_ptr => warp_ctl_if_dvstack_ptr,
            dcr_csr_if_valid => dcr_csr_if_valid,
            dcr_csr_if_addr => dcr_csr_if_addr,
            dcr_csr_if_mpm_class => dcr_csr_if_mpm_class,
            dcr_csr_if_value => dcr_csr_if_value,
            dcr_csr_if_ready => dcr_csr_if_ready
        );

    -- same phase as the oracle's `reg clk = 0; always #5 clk = ~clk`:
    -- rising edges at 5 + 10k ns, falling edges at 10 + 10k ns
    clkgen: process begin
        wait for 5 ns;
        while running loop
            clk <= L3D_1; wait for 5 ns;
            clk <= L3D_0; wait for 5 ns;
        end loop;
        wait;
    end process;

    replay: process
        file f : text open read_mode is "vectors.txt";
        variable l, l0 : line;
        variable first : boolean;
        variable v_reset : std_logic_vector(3 downto 0);
        variable v_lsu_client_if_0_req_ready : std_logic_vector(3 downto 0);
        variable v_lsu_client_if_0_rsp_valid : std_logic_vector(3 downto 0);
        variable v_lsu_client_if_0_rsp_data : std_logic_vector(131 downto 0);
        variable v_dispatch_if_0_valid : std_logic_vector(3 downto 0);
        variable v_dispatch_if_0_data : std_logic_vector(275 downto 0);
        variable v_dispatch_if_1_valid : std_logic_vector(3 downto 0);
        variable v_dispatch_if_1_data : std_logic_vector(275 downto 0);
        variable v_dispatch_if_2_valid : std_logic_vector(3 downto 0);
        variable v_dispatch_if_2_data : std_logic_vector(275 downto 0);
        variable v_dispatch_if_3_valid : std_logic_vector(3 downto 0);
        variable v_dispatch_if_3_data : std_logic_vector(275 downto 0);
        variable v_commit_if_0_ready : std_logic_vector(3 downto 0);
        variable v_commit_if_1_ready : std_logic_vector(3 downto 0);
        variable v_commit_if_2_ready : std_logic_vector(3 downto 0);
        variable v_commit_if_3_ready : std_logic_vector(3 downto 0);
        variable v_sched_csr_if_cycles : std_logic_vector(43 downto 0);
        variable v_sched_csr_if_instret : std_logic_vector(43 downto 0);
        variable v_sched_csr_if_active_warps : std_logic_vector(3 downto 0);
        variable v_sched_csr_if_thread_masks : std_logic_vector(3 downto 0);
        variable v_sched_csr_if_mscratch : std_logic_vector(31 downto 0);
        variable v_sched_csr_if_cta_csrs : std_logic_vector(331 downto 0);
        variable v_sched_csr_if_cta_lane : std_logic_vector(11 downto 0);
        variable v_sched_csr_if_csr_mstatus : std_logic_vector(31 downto 0);
        variable v_sched_csr_if_csr_mtvec : std_logic_vector(31 downto 0);
        variable v_sched_csr_if_csr_mepc : std_logic_vector(31 downto 0);
        variable v_sched_csr_if_csr_mcause : std_logic_vector(31 downto 0);
        variable v_sched_csr_if_csr_mtval : std_logic_vector(31 downto 0);
        variable v_warp_ctl_if_bar_phase : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_warp_pending_alm_empty : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_lsu_sched_drained : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_dvstack_ptr : std_logic_vector(3 downto 0);
        variable v_dcr_csr_if_valid : std_logic_vector(3 downto 0);
        variable v_dcr_csr_if_addr : std_logic_vector(11 downto 0);
        variable v_dcr_csr_if_mpm_class : std_logic_vector(7 downto 0);
        variable v_lsu_client_if_0_req_valid : std_logic_vector(3 downto 0);
        variable v_lsu_client_if_0_req_data : std_logic_vector(223 downto 0);
        variable v_lsu_client_if_0_rsp_ready : std_logic_vector(3 downto 0);
        variable v_dispatch_if_0_ready : std_logic_vector(3 downto 0);
        variable v_dispatch_if_1_ready : std_logic_vector(3 downto 0);
        variable v_dispatch_if_2_ready : std_logic_vector(3 downto 0);
        variable v_dispatch_if_3_ready : std_logic_vector(3 downto 0);
        variable v_commit_if_0_valid : std_logic_vector(3 downto 0);
        variable v_commit_if_0_data : std_logic_vector(115 downto 0);
        variable v_commit_if_1_valid : std_logic_vector(3 downto 0);
        variable v_commit_if_1_data : std_logic_vector(115 downto 0);
        variable v_commit_if_2_valid : std_logic_vector(3 downto 0);
        variable v_commit_if_2_data : std_logic_vector(115 downto 0);
        variable v_commit_if_3_valid : std_logic_vector(3 downto 0);
        variable v_commit_if_3_data : std_logic_vector(115 downto 0);
        variable v_sched_csr_if_csr_rd_wid : std_logic_vector(3 downto 0);
        variable v_sched_csr_if_csr_rd_cta_id : std_logic_vector(3 downto 0);
        variable v_sched_csr_if_csr_wr_valid : std_logic_vector(3 downto 0);
        variable v_sched_csr_if_csr_wr_wid : std_logic_vector(3 downto 0);
        variable v_sched_csr_if_csr_wr_data : std_logic_vector(31 downto 0);
        variable v_sched_csr_if_trap_csr_wr_valid : std_logic_vector(3 downto 0);
        variable v_sched_csr_if_trap_csr_wr_addr : std_logic_vector(11 downto 0);
        variable v_sched_csr_if_trap_csr_wr_data : std_logic_vector(31 downto 0);
        variable v_branch_ctl_if_0_valid : std_logic_vector(3 downto 0);
        variable v_branch_ctl_if_0_wid : std_logic_vector(3 downto 0);
        variable v_branch_ctl_if_0_taken : std_logic_vector(3 downto 0);
        variable v_branch_ctl_if_0_dest : std_logic_vector(31 downto 0);
        variable v_branch_ctl_if_0_is_trap : std_logic_vector(3 downto 0);
        variable v_branch_ctl_if_0_is_mret : std_logic_vector(3 downto 0);
        variable v_branch_ctl_if_0_trap_cause : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_wspawn_valid : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_tmc_valid : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_split_valid : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_sjoin_valid : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_bar_valid : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_wsync_valid : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_wid : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_wspawn : std_logic_vector(31 downto 0);
        variable v_warp_ctl_if_tmc : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_split : std_logic_vector(35 downto 0);
        variable v_warp_ctl_if_sjoin : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_bar : std_logic_vector(15 downto 0);
        variable v_warp_ctl_if_bar_addr : std_logic_vector(3 downto 0);
        variable v_warp_ctl_if_dvstack_wid : std_logic_vector(3 downto 0);
        variable v_dcr_csr_if_value : std_logic_vector(31 downto 0);
        variable v_dcr_csr_if_ready : std_logic_vector(3 downto 0);
        variable cyc, bad, shown : integer := 0;
        variable n_commit0, n_commit1, n_commit2, n_commit3, n_lsu_req, n_lsu_rsp, n_br : integer := 0;
        variable n_csr_wr, n_trap_wr, n_wctl : integer := 0;
        procedure chk(name : string; act, exp : std_logic_vector) is
        begin
            if not matches(act, exp) then
                bad := bad + 1;
                if shown < 40 then
                    shown := shown + 1;
                    report "cycle " & integer'image(cyc) & ": " & name & " mismatch act="
                        & to_hstring(act) & " exp=" & to_hstring(exp) severity warning;
                end if;
            end if;
        end procedure;
        procedure defined(name : string; e : std_logic_vector) is
        begin
            for i in e'range loop
                assert e(i) = '0' or e(i) = '1'
                    report "cycle " & integer'image(cyc) & ": expected " & name
                         & " is undefined after reset -- the compare would be vacuous"
                    severity failure;
            end loop;
        end procedure;
    begin
        -- Pre-history: the oracle's DUT sees its first rising edge (5 ns) with
        -- reset = 1 and the testbench's initial input values, which are what
        -- row 0 records.  Drive row 0 from time 0 (a copy of the line; the
        -- line itself is consumed again at the first falling edge).
        readline(f, l);
        l0 := new string'(l.all);
        rdhex(l0, v_reset); reset <= to_logic3d(v_reset(0));
        rdhex(l0, v_lsu_client_if_0_req_ready); lsu_client_if_0_req_ready <= to_logic3d(v_lsu_client_if_0_req_ready(0));
        rdhex(l0, v_lsu_client_if_0_rsp_valid); lsu_client_if_0_rsp_valid <= to_logic3d(v_lsu_client_if_0_rsp_valid(0));
        rdhex(l0, v_lsu_client_if_0_rsp_data); lsu_client_if_0_rsp_data <= slv2l3d(v_lsu_client_if_0_rsp_data(130 downto 0));
        rdhex(l0, v_dispatch_if_0_valid); dispatch_if_0_valid <= to_logic3d(v_dispatch_if_0_valid(0));
        rdhex(l0, v_dispatch_if_0_data); dispatch_if_0_data <= slv2l3d(v_dispatch_if_0_data(273 downto 0));
        rdhex(l0, v_dispatch_if_1_valid); dispatch_if_1_valid <= to_logic3d(v_dispatch_if_1_valid(0));
        rdhex(l0, v_dispatch_if_1_data); dispatch_if_1_data <= slv2l3d(v_dispatch_if_1_data(273 downto 0));
        rdhex(l0, v_dispatch_if_2_valid); dispatch_if_2_valid <= to_logic3d(v_dispatch_if_2_valid(0));
        rdhex(l0, v_dispatch_if_2_data); dispatch_if_2_data <= slv2l3d(v_dispatch_if_2_data(273 downto 0));
        rdhex(l0, v_dispatch_if_3_valid); dispatch_if_3_valid <= to_logic3d(v_dispatch_if_3_valid(0));
        rdhex(l0, v_dispatch_if_3_data); dispatch_if_3_data <= slv2l3d(v_dispatch_if_3_data(273 downto 0));
        rdhex(l0, v_commit_if_0_ready); commit_if_0_ready <= to_logic3d(v_commit_if_0_ready(0));
        rdhex(l0, v_commit_if_1_ready); commit_if_1_ready <= to_logic3d(v_commit_if_1_ready(0));
        rdhex(l0, v_commit_if_2_ready); commit_if_2_ready <= to_logic3d(v_commit_if_2_ready(0));
        rdhex(l0, v_commit_if_3_ready); commit_if_3_ready <= to_logic3d(v_commit_if_3_ready(0));
        rdhex(l0, v_sched_csr_if_cycles); sched_csr_if_cycles <= slv2l3d(v_sched_csr_if_cycles(43 downto 0));
        rdhex(l0, v_sched_csr_if_instret); sched_csr_if_instret <= slv2l3d(v_sched_csr_if_instret(43 downto 0));
        rdhex(l0, v_sched_csr_if_active_warps); sched_csr_if_active_warps <= slv2l3d(v_sched_csr_if_active_warps(1 downto 0));
        rdhex(l0, v_sched_csr_if_thread_masks); sched_csr_if_thread_masks <= slv2l3d(v_sched_csr_if_thread_masks(3 downto 0));
        rdhex(l0, v_sched_csr_if_mscratch); sched_csr_if_mscratch <= slv2l3d(v_sched_csr_if_mscratch(31 downto 0));
        rdhex(l0, v_sched_csr_if_cta_csrs); sched_csr_if_cta_csrs <= slv2l3d(v_sched_csr_if_cta_csrs(330 downto 0));
        rdhex(l0, v_sched_csr_if_cta_lane); sched_csr_if_cta_lane <= slv2l3d(v_sched_csr_if_cta_lane(11 downto 0));
        rdhex(l0, v_sched_csr_if_csr_mstatus); sched_csr_if_csr_mstatus <= slv2l3d(v_sched_csr_if_csr_mstatus(31 downto 0));
        rdhex(l0, v_sched_csr_if_csr_mtvec); sched_csr_if_csr_mtvec <= slv2l3d(v_sched_csr_if_csr_mtvec(31 downto 0));
        rdhex(l0, v_sched_csr_if_csr_mepc); sched_csr_if_csr_mepc <= slv2l3d(v_sched_csr_if_csr_mepc(31 downto 0));
        rdhex(l0, v_sched_csr_if_csr_mcause); sched_csr_if_csr_mcause <= slv2l3d(v_sched_csr_if_csr_mcause(31 downto 0));
        rdhex(l0, v_sched_csr_if_csr_mtval); sched_csr_if_csr_mtval <= slv2l3d(v_sched_csr_if_csr_mtval(31 downto 0));
        rdhex(l0, v_warp_ctl_if_bar_phase); warp_ctl_if_bar_phase <= to_logic3d(v_warp_ctl_if_bar_phase(0));
        rdhex(l0, v_warp_ctl_if_warp_pending_alm_empty); warp_ctl_if_warp_pending_alm_empty <= slv2l3d(v_warp_ctl_if_warp_pending_alm_empty(1 downto 0));
        rdhex(l0, v_warp_ctl_if_lsu_sched_drained); warp_ctl_if_lsu_sched_drained <= to_logic3d(v_warp_ctl_if_lsu_sched_drained(0));
        rdhex(l0, v_warp_ctl_if_dvstack_ptr); warp_ctl_if_dvstack_ptr <= to_logic3d(v_warp_ctl_if_dvstack_ptr(0));
        rdhex(l0, v_dcr_csr_if_valid); dcr_csr_if_valid <= to_logic3d(v_dcr_csr_if_valid(0));
        rdhex(l0, v_dcr_csr_if_addr); dcr_csr_if_addr <= slv2l3d(v_dcr_csr_if_addr(11 downto 0));
        rdhex(l0, v_dcr_csr_if_mpm_class); dcr_csr_if_mpm_class <= slv2l3d(v_dcr_csr_if_mpm_class(7 downto 0));
        deallocate(l0);
        first := true;
        while first or not endfile(f) loop
            if not first then readline(f, l); end if;
            first := false;
            -- mirror the oracle recorder: inputs applied AT the falling edge,
            -- outputs compared 1 ns later (they reflect the preceding rising edge)
            wait until clk = L3D_0;
            rdhex(l, v_reset); reset <= to_logic3d(v_reset(0));
            rdhex(l, v_lsu_client_if_0_req_ready); lsu_client_if_0_req_ready <= to_logic3d(v_lsu_client_if_0_req_ready(0));
            rdhex(l, v_lsu_client_if_0_rsp_valid); lsu_client_if_0_rsp_valid <= to_logic3d(v_lsu_client_if_0_rsp_valid(0));
            rdhex(l, v_lsu_client_if_0_rsp_data); lsu_client_if_0_rsp_data <= slv2l3d(v_lsu_client_if_0_rsp_data(130 downto 0));
            rdhex(l, v_dispatch_if_0_valid); dispatch_if_0_valid <= to_logic3d(v_dispatch_if_0_valid(0));
            rdhex(l, v_dispatch_if_0_data); dispatch_if_0_data <= slv2l3d(v_dispatch_if_0_data(273 downto 0));
            rdhex(l, v_dispatch_if_1_valid); dispatch_if_1_valid <= to_logic3d(v_dispatch_if_1_valid(0));
            rdhex(l, v_dispatch_if_1_data); dispatch_if_1_data <= slv2l3d(v_dispatch_if_1_data(273 downto 0));
            rdhex(l, v_dispatch_if_2_valid); dispatch_if_2_valid <= to_logic3d(v_dispatch_if_2_valid(0));
            rdhex(l, v_dispatch_if_2_data); dispatch_if_2_data <= slv2l3d(v_dispatch_if_2_data(273 downto 0));
            rdhex(l, v_dispatch_if_3_valid); dispatch_if_3_valid <= to_logic3d(v_dispatch_if_3_valid(0));
            rdhex(l, v_dispatch_if_3_data); dispatch_if_3_data <= slv2l3d(v_dispatch_if_3_data(273 downto 0));
            rdhex(l, v_commit_if_0_ready); commit_if_0_ready <= to_logic3d(v_commit_if_0_ready(0));
            rdhex(l, v_commit_if_1_ready); commit_if_1_ready <= to_logic3d(v_commit_if_1_ready(0));
            rdhex(l, v_commit_if_2_ready); commit_if_2_ready <= to_logic3d(v_commit_if_2_ready(0));
            rdhex(l, v_commit_if_3_ready); commit_if_3_ready <= to_logic3d(v_commit_if_3_ready(0));
            rdhex(l, v_sched_csr_if_cycles); sched_csr_if_cycles <= slv2l3d(v_sched_csr_if_cycles(43 downto 0));
            rdhex(l, v_sched_csr_if_instret); sched_csr_if_instret <= slv2l3d(v_sched_csr_if_instret(43 downto 0));
            rdhex(l, v_sched_csr_if_active_warps); sched_csr_if_active_warps <= slv2l3d(v_sched_csr_if_active_warps(1 downto 0));
            rdhex(l, v_sched_csr_if_thread_masks); sched_csr_if_thread_masks <= slv2l3d(v_sched_csr_if_thread_masks(3 downto 0));
            rdhex(l, v_sched_csr_if_mscratch); sched_csr_if_mscratch <= slv2l3d(v_sched_csr_if_mscratch(31 downto 0));
            rdhex(l, v_sched_csr_if_cta_csrs); sched_csr_if_cta_csrs <= slv2l3d(v_sched_csr_if_cta_csrs(330 downto 0));
            rdhex(l, v_sched_csr_if_cta_lane); sched_csr_if_cta_lane <= slv2l3d(v_sched_csr_if_cta_lane(11 downto 0));
            rdhex(l, v_sched_csr_if_csr_mstatus); sched_csr_if_csr_mstatus <= slv2l3d(v_sched_csr_if_csr_mstatus(31 downto 0));
            rdhex(l, v_sched_csr_if_csr_mtvec); sched_csr_if_csr_mtvec <= slv2l3d(v_sched_csr_if_csr_mtvec(31 downto 0));
            rdhex(l, v_sched_csr_if_csr_mepc); sched_csr_if_csr_mepc <= slv2l3d(v_sched_csr_if_csr_mepc(31 downto 0));
            rdhex(l, v_sched_csr_if_csr_mcause); sched_csr_if_csr_mcause <= slv2l3d(v_sched_csr_if_csr_mcause(31 downto 0));
            rdhex(l, v_sched_csr_if_csr_mtval); sched_csr_if_csr_mtval <= slv2l3d(v_sched_csr_if_csr_mtval(31 downto 0));
            rdhex(l, v_warp_ctl_if_bar_phase); warp_ctl_if_bar_phase <= to_logic3d(v_warp_ctl_if_bar_phase(0));
            rdhex(l, v_warp_ctl_if_warp_pending_alm_empty); warp_ctl_if_warp_pending_alm_empty <= slv2l3d(v_warp_ctl_if_warp_pending_alm_empty(1 downto 0));
            rdhex(l, v_warp_ctl_if_lsu_sched_drained); warp_ctl_if_lsu_sched_drained <= to_logic3d(v_warp_ctl_if_lsu_sched_drained(0));
            rdhex(l, v_warp_ctl_if_dvstack_ptr); warp_ctl_if_dvstack_ptr <= to_logic3d(v_warp_ctl_if_dvstack_ptr(0));
            rdhex(l, v_dcr_csr_if_valid); dcr_csr_if_valid <= to_logic3d(v_dcr_csr_if_valid(0));
            rdhex(l, v_dcr_csr_if_addr); dcr_csr_if_addr <= slv2l3d(v_dcr_csr_if_addr(11 downto 0));
            rdhex(l, v_dcr_csr_if_mpm_class); dcr_csr_if_mpm_class <= slv2l3d(v_dcr_csr_if_mpm_class(7 downto 0));
            rdbin(l, v_lsu_client_if_0_req_valid);
            rdbin(l, v_lsu_client_if_0_req_data);
            rdbin(l, v_lsu_client_if_0_rsp_ready);
            rdbin(l, v_dispatch_if_0_ready);
            rdbin(l, v_dispatch_if_1_ready);
            rdbin(l, v_dispatch_if_2_ready);
            rdbin(l, v_dispatch_if_3_ready);
            rdbin(l, v_commit_if_0_valid);
            rdbin(l, v_commit_if_0_data);
            rdbin(l, v_commit_if_1_valid);
            rdbin(l, v_commit_if_1_data);
            rdbin(l, v_commit_if_2_valid);
            rdbin(l, v_commit_if_2_data);
            rdbin(l, v_commit_if_3_valid);
            rdbin(l, v_commit_if_3_data);
            rdbin(l, v_sched_csr_if_csr_rd_wid);
            rdbin(l, v_sched_csr_if_csr_rd_cta_id);
            rdbin(l, v_sched_csr_if_csr_wr_valid);
            rdbin(l, v_sched_csr_if_csr_wr_wid);
            rdbin(l, v_sched_csr_if_csr_wr_data);
            rdbin(l, v_sched_csr_if_trap_csr_wr_valid);
            rdbin(l, v_sched_csr_if_trap_csr_wr_addr);
            rdbin(l, v_sched_csr_if_trap_csr_wr_data);
            rdbin(l, v_branch_ctl_if_0_valid);
            rdbin(l, v_branch_ctl_if_0_wid);
            rdbin(l, v_branch_ctl_if_0_taken);
            rdbin(l, v_branch_ctl_if_0_dest);
            rdbin(l, v_branch_ctl_if_0_is_trap);
            rdbin(l, v_branch_ctl_if_0_is_mret);
            rdbin(l, v_branch_ctl_if_0_trap_cause);
            rdbin(l, v_warp_ctl_if_wspawn_valid);
            rdbin(l, v_warp_ctl_if_tmc_valid);
            rdbin(l, v_warp_ctl_if_split_valid);
            rdbin(l, v_warp_ctl_if_sjoin_valid);
            rdbin(l, v_warp_ctl_if_bar_valid);
            rdbin(l, v_warp_ctl_if_wsync_valid);
            rdbin(l, v_warp_ctl_if_wid);
            rdbin(l, v_warp_ctl_if_wspawn);
            rdbin(l, v_warp_ctl_if_tmc);
            rdbin(l, v_warp_ctl_if_split);
            rdbin(l, v_warp_ctl_if_sjoin);
            rdbin(l, v_warp_ctl_if_bar);
            rdbin(l, v_warp_ctl_if_bar_addr);
            rdbin(l, v_warp_ctl_if_dvstack_wid);
            rdbin(l, v_dcr_csr_if_value);
            rdbin(l, v_dcr_csr_if_ready);
            wait for 1 ns;
            -- handshake expectations must be defined once reset is released
            if v_reset(0) = '0' then
                defined("lsu_client_if_0_req_valid", v_lsu_client_if_0_req_valid(0 downto 0));
                defined("lsu_client_if_0_rsp_ready", v_lsu_client_if_0_rsp_ready(0 downto 0));
                defined("dispatch_if_0_ready", v_dispatch_if_0_ready(0 downto 0));
                defined("dispatch_if_1_ready", v_dispatch_if_1_ready(0 downto 0));
                defined("dispatch_if_2_ready", v_dispatch_if_2_ready(0 downto 0));
                defined("dispatch_if_3_ready", v_dispatch_if_3_ready(0 downto 0));
                defined("commit_if_0_valid", v_commit_if_0_valid(0 downto 0));
                defined("commit_if_1_valid", v_commit_if_1_valid(0 downto 0));
                defined("commit_if_2_valid", v_commit_if_2_valid(0 downto 0));
                defined("commit_if_3_valid", v_commit_if_3_valid(0 downto 0));
                defined("sched_csr_if_csr_wr_valid", v_sched_csr_if_csr_wr_valid(0 downto 0));
                defined("sched_csr_if_trap_csr_wr_valid", v_sched_csr_if_trap_csr_wr_valid(0 downto 0));
                defined("branch_ctl_if_0_valid", v_branch_ctl_if_0_valid(0 downto 0));
                defined("warp_ctl_if_wspawn_valid", v_warp_ctl_if_wspawn_valid(0 downto 0));
                defined("warp_ctl_if_tmc_valid", v_warp_ctl_if_tmc_valid(0 downto 0));
                defined("warp_ctl_if_split_valid", v_warp_ctl_if_split_valid(0 downto 0));
                defined("warp_ctl_if_sjoin_valid", v_warp_ctl_if_sjoin_valid(0 downto 0));
                defined("warp_ctl_if_bar_valid", v_warp_ctl_if_bar_valid(0 downto 0));
                defined("warp_ctl_if_wsync_valid", v_warp_ctl_if_wsync_valid(0 downto 0));
                defined("dcr_csr_if_ready", v_dcr_csr_if_ready(0 downto 0));
            end if;
            chk("lsu_client_if_0_req_valid", to_std_logic_vector(lsu_client_if_0_req_valid), v_lsu_client_if_0_req_valid(0 downto 0));
            chk("lsu_client_if_0_req_data", to_std_logic_vector(lsu_client_if_0_req_data), v_lsu_client_if_0_req_data(221 downto 0));
            chk("lsu_client_if_0_rsp_ready", to_std_logic_vector(lsu_client_if_0_rsp_ready), v_lsu_client_if_0_rsp_ready(0 downto 0));
            chk("dispatch_if_0_ready", to_std_logic_vector(dispatch_if_0_ready), v_dispatch_if_0_ready(0 downto 0));
            chk("dispatch_if_1_ready", to_std_logic_vector(dispatch_if_1_ready), v_dispatch_if_1_ready(0 downto 0));
            chk("dispatch_if_2_ready", to_std_logic_vector(dispatch_if_2_ready), v_dispatch_if_2_ready(0 downto 0));
            chk("dispatch_if_3_ready", to_std_logic_vector(dispatch_if_3_ready), v_dispatch_if_3_ready(0 downto 0));
            chk("commit_if_0_valid", to_std_logic_vector(commit_if_0_valid), v_commit_if_0_valid(0 downto 0));
            chk("commit_if_0_data", to_std_logic_vector(commit_if_0_data), v_commit_if_0_data(114 downto 0));
            chk("commit_if_1_valid", to_std_logic_vector(commit_if_1_valid), v_commit_if_1_valid(0 downto 0));
            chk("commit_if_1_data", to_std_logic_vector(commit_if_1_data), v_commit_if_1_data(114 downto 0));
            chk("commit_if_2_valid", to_std_logic_vector(commit_if_2_valid), v_commit_if_2_valid(0 downto 0));
            chk("commit_if_2_data", to_std_logic_vector(commit_if_2_data), v_commit_if_2_data(114 downto 0));
            chk("commit_if_3_valid", to_std_logic_vector(commit_if_3_valid), v_commit_if_3_valid(0 downto 0));
            chk("commit_if_3_data", to_std_logic_vector(commit_if_3_data), v_commit_if_3_data(114 downto 0));
            chk("sched_csr_if_csr_rd_wid", to_std_logic_vector(sched_csr_if_csr_rd_wid), v_sched_csr_if_csr_rd_wid(0 downto 0));
            chk("sched_csr_if_csr_rd_cta_id", to_std_logic_vector(sched_csr_if_csr_rd_cta_id), v_sched_csr_if_csr_rd_cta_id(0 downto 0));
            chk("sched_csr_if_csr_wr_valid", to_std_logic_vector(sched_csr_if_csr_wr_valid), v_sched_csr_if_csr_wr_valid(0 downto 0));
            chk("sched_csr_if_csr_wr_wid", to_std_logic_vector(sched_csr_if_csr_wr_wid), v_sched_csr_if_csr_wr_wid(0 downto 0));
            chk("sched_csr_if_csr_wr_data", to_std_logic_vector(sched_csr_if_csr_wr_data), v_sched_csr_if_csr_wr_data(31 downto 0));
            chk("sched_csr_if_trap_csr_wr_valid", to_std_logic_vector(sched_csr_if_trap_csr_wr_valid), v_sched_csr_if_trap_csr_wr_valid(0 downto 0));
            chk("sched_csr_if_trap_csr_wr_addr", to_std_logic_vector(sched_csr_if_trap_csr_wr_addr), v_sched_csr_if_trap_csr_wr_addr(11 downto 0));
            chk("sched_csr_if_trap_csr_wr_data", to_std_logic_vector(sched_csr_if_trap_csr_wr_data), v_sched_csr_if_trap_csr_wr_data(31 downto 0));
            chk("branch_ctl_if_0_valid", to_std_logic_vector(branch_ctl_if_0_valid), v_branch_ctl_if_0_valid(0 downto 0));
            chk("branch_ctl_if_0_wid", to_std_logic_vector(branch_ctl_if_0_wid), v_branch_ctl_if_0_wid(0 downto 0));
            chk("branch_ctl_if_0_taken", to_std_logic_vector(branch_ctl_if_0_taken), v_branch_ctl_if_0_taken(0 downto 0));
            chk("branch_ctl_if_0_dest", to_std_logic_vector(branch_ctl_if_0_dest), v_branch_ctl_if_0_dest(29 downto 0));
            chk("branch_ctl_if_0_is_trap", to_std_logic_vector(branch_ctl_if_0_is_trap), v_branch_ctl_if_0_is_trap(0 downto 0));
            chk("branch_ctl_if_0_is_mret", to_std_logic_vector(branch_ctl_if_0_is_mret), v_branch_ctl_if_0_is_mret(0 downto 0));
            chk("branch_ctl_if_0_trap_cause", to_std_logic_vector(branch_ctl_if_0_trap_cause), v_branch_ctl_if_0_trap_cause(3 downto 0));
            chk("warp_ctl_if_wspawn_valid", to_std_logic_vector(warp_ctl_if_wspawn_valid), v_warp_ctl_if_wspawn_valid(0 downto 0));
            chk("warp_ctl_if_tmc_valid", to_std_logic_vector(warp_ctl_if_tmc_valid), v_warp_ctl_if_tmc_valid(0 downto 0));
            chk("warp_ctl_if_split_valid", to_std_logic_vector(warp_ctl_if_split_valid), v_warp_ctl_if_split_valid(0 downto 0));
            chk("warp_ctl_if_sjoin_valid", to_std_logic_vector(warp_ctl_if_sjoin_valid), v_warp_ctl_if_sjoin_valid(0 downto 0));
            chk("warp_ctl_if_bar_valid", to_std_logic_vector(warp_ctl_if_bar_valid), v_warp_ctl_if_bar_valid(0 downto 0));
            chk("warp_ctl_if_wsync_valid", to_std_logic_vector(warp_ctl_if_wsync_valid), v_warp_ctl_if_wsync_valid(0 downto 0));
            chk("warp_ctl_if_wid", to_std_logic_vector(warp_ctl_if_wid), v_warp_ctl_if_wid(0 downto 0));
            chk("warp_ctl_if_wspawn", to_std_logic_vector(warp_ctl_if_wspawn), v_warp_ctl_if_wspawn(31 downto 0));
            chk("warp_ctl_if_tmc", to_std_logic_vector(warp_ctl_if_tmc), v_warp_ctl_if_tmc(1 downto 0));
            chk("warp_ctl_if_split", to_std_logic_vector(warp_ctl_if_split), v_warp_ctl_if_split(34 downto 0));
            chk("warp_ctl_if_sjoin", to_std_logic_vector(warp_ctl_if_sjoin), v_warp_ctl_if_sjoin(2 downto 0));
            chk("warp_ctl_if_bar", to_std_logic_vector(warp_ctl_if_bar), v_warp_ctl_if_bar(12 downto 0));
            chk("warp_ctl_if_bar_addr", to_std_logic_vector(warp_ctl_if_bar_addr), v_warp_ctl_if_bar_addr(3 downto 0));
            chk("warp_ctl_if_dvstack_wid", to_std_logic_vector(warp_ctl_if_dvstack_wid), v_warp_ctl_if_dvstack_wid(0 downto 0));
            chk("dcr_csr_if_value", to_std_logic_vector(dcr_csr_if_value), v_dcr_csr_if_value(31 downto 0));
            chk("dcr_csr_if_ready", to_std_logic_vector(dcr_csr_if_ready), v_dcr_csr_if_ready(0 downto 0));
            -- coverage tallies from the NVC DUT's own outputs (a handshake
            -- seen here is consumed by the next rising edge; the ready inputs
            -- are this bench's, driven from the vector at the falling edge)
            if commit_if_0_valid = L3D_1 and commit_if_0_ready = L3D_1 then n_commit0 := n_commit0 + 1; end if;
            if commit_if_1_valid = L3D_1 and commit_if_1_ready = L3D_1 then n_commit1 := n_commit1 + 1; end if;
            if commit_if_2_valid = L3D_1 and commit_if_2_ready = L3D_1 then n_commit2 := n_commit2 + 1; end if;
            if commit_if_3_valid = L3D_1 and commit_if_3_ready = L3D_1 then n_commit3 := n_commit3 + 1; end if;
            if lsu_client_if_0_req_valid = L3D_1 and lsu_client_if_0_req_ready = L3D_1 then n_lsu_req := n_lsu_req + 1; end if;
            if lsu_client_if_0_rsp_valid = L3D_1 and lsu_client_if_0_rsp_ready = L3D_1 then n_lsu_rsp := n_lsu_rsp + 1; end if;
            if branch_ctl_if_0_valid = L3D_1 then n_br := n_br + 1; end if;
            if sched_csr_if_csr_wr_valid = L3D_1 then n_csr_wr := n_csr_wr + 1; end if;
            if sched_csr_if_trap_csr_wr_valid = L3D_1 then n_trap_wr := n_trap_wr + 1; end if;
            if warp_ctl_if_wspawn_valid = L3D_1 or warp_ctl_if_tmc_valid = L3D_1 or warp_ctl_if_split_valid = L3D_1
               or warp_ctl_if_sjoin_valid = L3D_1 or warp_ctl_if_bar_valid = L3D_1 or warp_ctl_if_wsync_valid = L3D_1 then
                n_wctl := n_wctl + 1;
            end if;
            cyc := cyc + 1;
        end loop;
        running <= false;
        if bad = 0 then
            report "PASS: " & integer'image(cyc) & " cycles replayed and compared from cycle 0 (outputs bit-exact, x = don't-care); "
                 & "DUT commits alu/lsu/sfu/fpu="
                 & integer'image(n_commit0) & "/" & integer'image(n_commit1) & "/" & integer'image(n_commit2) & "/" & integer'image(n_commit3)
                 & ", lsu req/rsp=" & integer'image(n_lsu_req) & "/" & integer'image(n_lsu_rsp)
                 & ", branches=" & integer'image(n_br) & ", csr_wr=" & integer'image(n_csr_wr)
                 & ", trap_csr_wr=" & integer'image(n_trap_wr) & ", warp_ctl=" & integer'image(n_wctl)
                 & " -- all outputs identical to the vvp oracle every cycle";
        else
            report "FAIL: " & integer'image(bad) & " output mismatches over " & integer'image(cyc) & " cycles" severity failure;
        end if;
        wait;
    end process;
end architecture;
